[mypy]
ignore_missing_imports = True
exclude = ^admin/

[mypy-pytz]
ignore_missing_imports = True

[mypy-scripts.ccl_leveldb]
ignore_errors = True

[mypy-scripts.ccl_simplesnappy]
ignore_errors = True

[mypy-scripts.parse3]
ignore_errors = True

[mypy-scripts.ccl_segb.*]
ignore_errors = True

[mypy-admin.*]
ignore_errors = True

[mypy-admin.scripts.*]
ignore_errors = True

[mypy-admin.test.*]
ignore_errors = True

[mypy-admin.test.scripts.*]
ignore_errors = True
