"""The committed third-party notices must cover the unifiedlog_iterator binary a build ships.

bin/THIRD-PARTY-NOTICES-unifiedlog_iterator.txt lists the Rust crates the binary links,
with their license texts. It is generated by admin/scripts/make_unifiedlog_notices.py and
committed; the test builds then run its --verify option on the binary they fetched, which
compares the crate versions whose crates.io source paths the binary embeds with the list.
Everything here runs offline, on every Python the project supports.
"""
import importlib.util
import pathlib
import tempfile
import unittest

REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
NOTICES = REPO_ROOT / 'bin' / 'THIRD-PARTY-NOTICES-unifiedlog_iterator.txt'

_SPEC = importlib.util.spec_from_file_location(
    'make_unifiedlog_notices', REPO_ROOT / 'admin' / 'scripts' / 'make_unifiedlog_notices.py')
notices = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(notices)

# How a Cargo registry source path appears inside a release binary, on each platform.
POSIX_PATH = b'/home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/nom-8.0.0/src/'
WINDOWS_PATH = (b'C:\\Users\\runneradmin\\.cargo\\registry\\src\\'
                b'index.crates.io-1949cf8c6b5b557f\\windows-sys-0.61.0\\src\\')


class TestCommittedNotices(unittest.TestCase):
    """The file that ships must parse, and must carry a section for every crate it lists."""

    def test_the_list_parses(self):
        listed = notices.listed_crates(NOTICES)
        self.assertGreater(len(listed), 0)
        for name, version in listed:
            self.assertRegex(version, r'^\d+\.\d+\.\d+', f'{name} has no version')

    def test_every_listed_crate_has_its_own_section(self):
        text = NOTICES.read_text(encoding='utf-8')
        for name, version in notices.listed_crates(NOTICES):
            with self.subTest(crate=name):
                self.assertIn(f'\n{"=" * 78}\n{name} {version}\nLicense: ', text)

    def test_the_header_names_the_pinned_release(self):
        self.assertTrue(NOTICES.read_text(encoding='utf-8').startswith(
            f'Third-party notices for unifiedlog_iterator {notices.PINNED_VERSION}\n'))


class TestEmbeddedCrates(unittest.TestCase):
    """Crate versions are read from registry source paths, with either separator."""

    def _binary(self, data):
        handle = tempfile.NamedTemporaryFile(delete=False)  # pylint: disable=consider-using-with
        handle.write(data)
        handle.close()
        self.addCleanup(pathlib.Path(handle.name).unlink)
        return handle.name

    def test_posix_and_windows_paths_are_both_read(self):
        path = self._binary(b'\x00junk' + POSIX_PATH + b'lib.rs\x00' + WINDOWS_PATH + b'lib.rs')
        self.assertEqual(notices.embedded_crates(path),
                         {('nom', '8.0.0'), ('windows-sys', '0.61.0')})

    def test_a_path_outside_the_registry_is_ignored(self):
        path = self._binary(b'/rustc/' + b'0' * 40 + b'/library/core/src/')
        self.assertEqual(notices.embedded_crates(path), set())

    def test_verify_passes_when_every_embedded_crate_is_listed(self):
        listed = sorted(notices.listed_crates(NOTICES))
        name, version = listed[0]
        data = (b'/r/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/'
                + f'{name}-{version}/src/lib.rs'.encode())
        notices.verify([self._binary(data)], NOTICES)

    def test_verify_refuses_a_crate_the_list_lacks(self):
        data = POSIX_PATH.replace(b'nom-8.0.0', b'nom-99.0.0')
        with self.assertRaises(SystemExit):
            notices.verify([self._binary(data)], NOTICES)

    def test_verify_refuses_a_binary_that_names_no_crate(self):
        # A build with its paths stripped would pass any list; it proves nothing.
        with self.assertRaises(SystemExit):
            notices.verify([self._binary(b'no registry paths here')], NOTICES)


class TestBinaryKind(unittest.TestCase):
    """The build log names the platform of the binary it checked."""

    def test_headers(self):
        self.assertEqual(notices.binary_kind(b'\xcf\xfa\xed\xfe\x0c\x00\x00\x01'), 'Mach-O arm64')
        elf = bytearray(64)
        elf[:4] = b'\x7fELF'
        elf[18:20] = (0x3e).to_bytes(2, 'little')
        self.assertEqual(notices.binary_kind(bytes(elf)), 'ELF x86_64')
        pe = bytearray(0x100)
        pe[:2] = b'MZ'
        pe[0x3c:0x40] = (0x80).to_bytes(4, 'little')
        pe[0x80:0x84] = b'PE\x00\x00'
        pe[0x84:0x86] = (0x8664).to_bytes(2, 'little')
        self.assertEqual(notices.binary_kind(bytes(pe)), 'PE x86_64')
        self.assertEqual(notices.binary_kind(b'text'), 'unrecognised')


if __name__ == '__main__':
    unittest.main()
