__artifacts_v2__ = {
'Ph035iCloudSharedLinkAssetsPhDaPsql': {
'name': 'Ph035-iCloud Shared Link Assets-PhDaPsql',
'description': 'Assets from PhotoData/Photos.sqlite with stored ZASSET.ZSAVEDASSETTYPE 8, joined to share and participant records through ZASSET.ZMOMENTSHARE. Multiple participants can produce multiple rows per asset; missing share or participant records remain blank. Queries support iOS 14 through 25, with unsupported versions returning no rows. Enum fields report raw stored values. Registered real samples have returned no qualifying rows.',
'author': '@AlexisBrignoni, Codex',
'creation_date': '2026-05-28',
'last_update_date': '2026-10-05',
'version': '6.0',
'date': '2026-05-27',
'requirements': 'Acquisition that contains PhotoData-Photos.sqlite',
'category': 'Photos.sqlite',
'notes': 'Original parser and Photos.sqlite research: Scott Koenig, https://theforensicscooter.com/2024/05/18/ileapp-parsers-photos-sqlite-queries/. Raw enum projections preserve stored NULL and unknown values; per-value interpretations are not emitted.',
'paths': ('*/PhotoData/Photos.sqlite*',),
"output_types": ["standard", "tsv", "none"],
"artifact_icon": "link",
'sample_data': {
'ctf2020_ios12': 'iOS 12.4 | not queried, the code returns before reading the database on versions below iOS 14',
'dexter_ios18': 'iOS 18.3.2 | 0 rows',
'felix_ios17': 'iOS 17.6.1 | 0 rows',
'fsfull002_ios17': 'iOS 17.1 | 0 rows',
'hc_ios18_7': 'iOS 18.7.8 | 0 rows',
'iphone11_ios17': 'iOS 17.3 | 0 rows',
'iphone12_ios18': 'iOS 18.7 | 0 rows',
'iphone14plus_ios18': 'iOS 18.0 | 0 rows',
'otto_ios17': 'iOS 17.5.1 | 0 rows',
'abe_ios16': 'iOS 16.5 | 0 rows',
'felix23_ios16': 'iOS 16.5 | 0 rows',
'hickman_ios13': 'iOS 13.3.1 | not queried, the code returns before reading the database on versions below iOS 14',
'hickman_ios14': 'iOS 14.3 | 0 rows',
'jess_ios15': 'iOS 15.0.2 | 0 rows',
'magnet_ios16': 'iOS 16.1.1 | 0 rows',
}
}
}

import os
from packaging import version
from scripts.ilapfuncs import artifact_processor, get_file_path, get_sqlite_db_records, null_absent_columns, logfunc, iOS

@artifact_processor
def Ph035iCloudSharedLinkAssetsPhDaPsql(context):
    files_found = context.get_files_found()
    report_folder = context.get_report_folder()
    source_path = ''
    for source_path in files_found:
        source_path = str(source_path)

        if source_path.endswith('.sqlite'):
            break

    if report_folder.endswith('/') or report_folder.endswith('\\'):
        report_folder = report_folder[:-1]
    iosversion = iOS.get_version()
    if (version.parse(iosversion) < version.parse("14")) or (version.parse(iosversion) >= version.parse("26")):
        logfunc("Unsupported version PhotoData-Photos.sqlite from iOS " + iosversion)
        return (), [], source_path
    if (version.parse(iosversion) >= version.parse("14")) & (version.parse(iosversion) < version.parse("15")):
        source_path = get_file_path(files_found,"Photos.sqlite")
        if source_path is None or not os.path.exists(source_path):
            logfunc(f"Photos.sqlite not found for iOS version {iosversion}")
            return (), [], source_path
        data_list = []

        query = '''
        SELECT
        DateTime(zShare.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Creation Date',
        DateTime(zShare.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Start Date',
        DateTime(zShare.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'zShare-End Date',
        DateTime(zShare.ZEXPIRYDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Expiry Date',
        DateTime(zAsset.ZDATECREATED + 978307200, 'UNIXEPOCH') AS 'zAsset-Date Created',
        zAsset.Z_PK AS 'zAsset-zPK',
        zAsset.ZDIRECTORY AS 'zAsset-Directory-Path',
        zAsset.ZFILENAME AS 'zAsset-Filename',
        zAddAssetAttr.ZORIGINALFILENAME AS 'zAddAssetAttr- Original Filename',
        zCldMast.ZORIGINALFILENAME AS 'zCldMast- Original Filename',
        zAddAssetAttr.ZCREATORBUNDLEID AS 'zAddAssetAttr- Creator Bundle ID',
        zAddAssetAttr.ZIMPORTEDBYDISPLAYNAME AS 'zAddAssetAttr- Imported By Display Name',
        zAsset.ZVISIBILITYSTATE AS 'zAsset-ZVISIBILITYSTATE Raw Value',
        zAsset.ZSAVEDASSETTYPE AS 'zAsset-ZSAVEDASSETTYPE Raw Value',
        zAddAssetAttr.ZSHARETYPE AS 'zAddAssetAttr-ZSHARETYPE Raw Value',
        DateTime(zAsset.ZSORTTOKEN + 978307200, 'UNIXEPOCH') AS 'zAsset- SortToken -CameraRoll',
        DateTime(zAsset.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Added Date',
        DateTime(zCldMast.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'zCldMast-Creation Date',
        zAddAssetAttr.ZTIMEZONENAME AS 'zAddAssetAttr-Time Zone Name',
        zAddAssetAttr.ZEXIFTIMESTAMPSTRING AS 'zAddAssetAttr-EXIF-String',
        DateTime(zAsset.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Modification Date',
        DateTime(zAsset.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Last Shared Date',
        DateTime(zAsset.ZTRASHEDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Trashed Date',
        zAddAssetAttr.Z_PK AS 'zAddAssetAttr-zPK',
        zAsset.ZUUID AS 'zAsset-UUID = store.cloudphotodb',
        zAddAssetAttr.ZMASTERFINGERPRINT AS 'zAddAssetAttr-Master Fingerprint',
        zShare.ZUUID AS 'zShare-UUID',
        zShare.ZORIGINATINGSCOPEIDENTIFIER AS 'zShare-Originating Scope ID',
        zShare.ZSTATUS AS 'zShare-ZSTATUS Raw Value',
        zShare.ZSCOPETYPE AS 'zShare-ZSCOPETYPE Raw Value',
        zShare.ZASSETCOUNT AS 'zShare-Asset Count-CMM',
        zShare.ZFORCESYNCATTEMPTED AS 'zShare-Force Sync Attempted-CMM',  
        zShare.ZPHOTOSCOUNT AS 'zShare-Photos Count-CMM',
        zShare.ZUPLOADEDPHOTOSCOUNT AS 'zShare-Uploaded Photos Count-CMM',
        zShare.ZVIDEOSCOUNT AS 'zShare-Videos Count-CMM',
        zShare.ZUPLOADEDVIDEOSCOUNT AS 'zShare-Uploaded Videos Count-CMM',
        zShare.ZSCOPEIDENTIFIER AS 'zShare-Scope ID',
        zShare.ZTITLE AS 'zShare-Title-SPL',
        zShare.ZSHAREURL AS 'zShare-Share URL',
        zShare.ZLOCALPUBLISHSTATE AS 'zShare-ZLOCALPUBLISHSTATE Raw Value',
        zShare.ZPUBLICPERMISSION AS 'zShare-ZPUBLICPERMISSION Raw Value',
        zSharePartic.ZACCEPTANCESTATUS AS 'zSharePartic-ZACCEPTANCESTATUS Raw Value',
        zSharePartic.ZUSERIDENTIFIER AS 'zSharePartic-User ID',
        zSharePartic.Z_PK AS 'zSharePartic-zPK',
        zSharePartic.ZEMAILADDRESS AS 'zSharePartic-Email Address',
        zSharePartic.ZPHONENUMBER AS 'zSharePartic-Phone Number',
        zSharePartic.ZISCURRENTUSER AS 'zSharePartic-ZISCURRENTUSER Raw Value',
        zSharePartic.ZROLE AS 'zSharePartic-ZROLE Raw Value',
        zSharePartic.ZPERMISSION AS 'zSharePartic-ZPERMISSION Raw Value',
        zShare.ZSHOULDNOTIFYONUPLOADCOMPLETION AS 'zShare-ZSHOULDNOTIFYONUPLOADCOMPLETION Raw Value',
        zShare.ZSHOULDIGNOREBUDGETS AS 'zShare-ZSHOULDIGNOREBUDGETS Raw Value',
        zShare.ZTRASHEDSTATE AS 'zShare-ZTRASHEDSTATE Raw Value',
        zShare.ZCLOUDDELETESTATE AS 'zShare-ZCLOUDDELETESTATE Raw Value',
        zShare.Z_ENT AS 'zShare-Z_ENT Raw Value'
        FROM ZASSET zAsset
            LEFT JOIN ZADDITIONALASSETATTRIBUTES zAddAssetAttr ON zAddAssetAttr.Z_PK = zAsset.ZADDITIONALATTRIBUTES
            LEFT JOIN ZEXTENDEDATTRIBUTES zExtAttr ON zExtAttr.Z_PK = zAsset.ZEXTENDEDATTRIBUTES
            LEFT JOIN ZCLOUDMASTER zCldMast ON zAsset.ZMASTER = zCldMast.Z_PK
            LEFT JOIN ZSHARE zShare ON zShare.Z_PK = zAsset.ZMOMENTSHARE
            LEFT JOIN ZSHAREPARTICIPANT zSharePartic ON zSharePartic.ZSHARE = zShare.Z_PK
        WHERE zAsset.ZSAVEDASSETTYPE = 8
        ORDER BY zShare.ZCREATIONDATE        
        '''

        db_records = get_sqlite_db_records(source_path, null_absent_columns(source_path, query))
        for row in db_records:
            data_list.append((row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9],
            row[10], row[11], row[12], row[13], row[14], row[15], row[16], row[17], row[18],
            row[19], row[20], row[21], row[22], row[23], row[24], row[25], row[26], row[27],
            row[28], row[29], row[30], row[31], row[32], row[33], row[34], row[35], row[36],
            row[37], row[38], row[39], row[40], row[41], row[42], row[43], row[44], row[45],
            row[46], row[47], row[48], row[49], row[50], row[51], row[52], row[53]))

        data_headers = (('zShare-Creation Date-0', 'datetime'),
        ('zShare-Start Date-1', 'datetime'),
        ('zShare-End Date-2', 'datetime'),
        ('zShare-Expiry Date-3', 'datetime'),
        ('zAsset-Date Created-4', 'datetime'),
        'zAsset-zPK-5',
        'zAsset-Directory-Path-6',
        'zAsset-Filename-7',
        'zAddAssetAttr- Original Filename-8',
        'zCldMast- Original Filename-9',
        'zAddAssetAttr- Creator Bundle ID-10',
        'zAddAssetAttr-Imported By Display Name-11',
        'zAsset-ZVISIBILITYSTATE Raw Value-12',
        'zAsset-ZSAVEDASSETTYPE Raw Value-13',
        'zAddAssetAttr-ZSHARETYPE Raw Value-14',
        ('zAsset- SortToken -CameraRoll-15', 'datetime'),
        ('zAsset-Added Date-16', 'datetime'),
        ('zCldMast-Creation Date-17', 'datetime'),
        'zAddAssetAttr-Time Zone Name-18',
        'zAddAssetAttr-EXIF-String-19',
        ('zAsset-Modification Date-20', 'datetime'),
        ('zAsset-Last Shared Date-21', 'datetime'),
        ('zAsset-Trashed Date-22', 'datetime'),
        'zAddAssetAttr-zPK-23',
        'zAsset-UUID = store.cloudphotodb-24',
        'zAddAssetAttr-Master Fingerprint-25',
        'zShare-UUID-26',
        'zShare-Originating Scope ID-27',
        'zShare-ZSTATUS Raw Value-28',
        'zShare-ZSCOPETYPE Raw Value-29',
        'zShare-Asset Count-CMM-30',
        'zShare-Force Sync Attempted-CMM-31',
        'zShare-Photos Count-CMM-32',
        'zShare-Uploaded Photos Count-CMM-33',
        'zShare-Videos Count-CMM-34',
        'zShare-Uploaded Videos Count-CMM-35',
        'zShare-Scope ID-36',
        'zShare-Title-SPL-37',
        'zShare-Share URL-38',
        'zShare-ZLOCALPUBLISHSTATE Raw Value-39',
        'zShare-ZPUBLICPERMISSION Raw Value-40',
        'zSharePartic-ZACCEPTANCESTATUS Raw Value-41',
        'zSharePartic-User ID-42',
        'zSharePartic-zPK-43',
        'zSharePartic-Email Address-44',
        'zSharePartic-Phone Number-45',
        'zSharePartic-ZISCURRENTUSER Raw Value-46',
        'zSharePartic-ZROLE Raw Value-47',
        'zSharePartic-ZPERMISSION Raw Value-48',
        'zShare-ZSHOULDNOTIFYONUPLOADCOMPLETION Raw Value-49',
        'zShare-ZSHOULDIGNOREBUDGETS Raw Value-50',
        'zShare-ZTRASHEDSTATE Raw Value-51',
        'zShare-ZCLOUDDELETESTATE Raw Value-52',
        'zShare-Z_ENT Raw Value-53')
# data_list = get_sqlite_db_records(source_path, null_absent_columns(source_path, query))

        return data_headers, data_list, source_path

    elif (version.parse(iosversion) >= version.parse("15")) & (version.parse(iosversion) < version.parse("16")):
        source_path = get_file_path(files_found,"Photos.sqlite")
        if source_path is None or not os.path.exists(source_path):
            logfunc(f"Photos.sqlite not found for iOS version {iosversion}")
            return (), [], source_path
        data_list = []

        query = '''
        SELECT
        DateTime(zShare.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Creation Date',
        DateTime(zShare.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Start Date',
        DateTime(zShare.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'zShare-End Date',
        DateTime(zShare.ZEXPIRYDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Expiry Date',
        DateTime(zAsset.ZDATECREATED + 978307200, 'UNIXEPOCH') AS 'zAsset-Date Created',
        zAsset.Z_PK AS 'zAsset-zPK',
        zAsset.ZDIRECTORY AS 'zAsset-Directory-Path',
        zAsset.ZFILENAME AS 'zAsset-Filename',
        zAddAssetAttr.ZORIGINALFILENAME AS 'zAddAssetAttr- Original Filename',
        zCldMast.ZORIGINALFILENAME AS 'zCldMast- Original Filename',
        zAddAssetAttr.ZSYNDICATIONIDENTIFIER AS 'zAddAssetAttr- Syndication Identifier-SWY-Files',
        zAsset.ZSYNDICATIONSTATE AS 'zAsset-ZSYNDICATIONSTATE Raw Value',
        zAsset.ZBUNDLESCOPE AS 'zAsset-ZBUNDLESCOPE Raw Value',
        zAddAssetAttr.ZIMPORTEDBYBUNDLEIDENTIFIER AS 'zAddAssetAttr- Imported by Bundle Identifier',
        zAddAssetAttr.ZIMPORTEDBYDISPLAYNAME AS 'zAddAssetAttr- Imported By Display Name',
        zAsset.ZVISIBILITYSTATE AS 'zAsset-ZVISIBILITYSTATE Raw Value',
        zAsset.ZSAVEDASSETTYPE AS 'zAsset-ZSAVEDASSETTYPE Raw Value',
        zAddAssetAttr.ZSHARETYPE AS 'zAddAssetAttr-ZSHARETYPE Raw Value',
        DateTime(zAsset.ZSORTTOKEN + 978307200, 'UNIXEPOCH') AS 'zAsset- SortToken -CameraRoll',
        DateTime(zAsset.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Added Date',
        DateTime(zCldMast.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'zCldMast-Creation Date',
        zAddAssetAttr.ZTIMEZONENAME AS 'zAddAssetAttr-Time Zone Name',
        zAddAssetAttr.ZEXIFTIMESTAMPSTRING AS 'zAddAssetAttr-EXIF-String',
        DateTime(zAsset.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Modification Date',
        DateTime(zAsset.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Last Shared Date',
        DateTime(zAsset.ZTRASHEDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Trashed Date',       
        zAddAssetAttr.Z_PK AS 'zAddAssetAttr-zPK',
        zAsset.ZUUID AS 'zAsset-UUID = store.cloudphotodb',
        zAddAssetAttr.ZMASTERFINGERPRINT AS 'zAddAssetAttr-Master Fingerprint',
        zShare.ZUUID AS 'zShare-UUID',
        zShare.ZORIGINATINGSCOPEIDENTIFIER AS 'zShare-Originating Scope ID',
        zShare.ZSTATUS AS 'zShare-ZSTATUS Raw Value',
        zShare.ZSCOPETYPE AS 'zShare-ZSCOPETYPE Raw Value',
        zShare.ZASSETCOUNT AS 'zShare-Asset Count-CMM',
        zShare.ZFORCESYNCATTEMPTED AS 'zShare-Force Sync Attempted-CMM',  
        zShare.ZPHOTOSCOUNT AS 'zShare-Photos Count-CMM',
        zShare.ZUPLOADEDPHOTOSCOUNT AS 'zShare-Uploaded Photos Count-CMM',
        zShare.ZVIDEOSCOUNT AS 'zShare-Videos Count-CMM',
        zShare.ZUPLOADEDVIDEOSCOUNT AS 'zShare-Uploaded Videos Count-CMM',
        zShare.ZSCOPEIDENTIFIER AS 'zShare-Scope ID',
        zShare.ZTITLE AS 'zShare-Title-SPL',
        zShare.ZSHAREURL AS 'zShare-Share URL',
        zShare.ZLOCALPUBLISHSTATE AS 'zShare-ZLOCALPUBLISHSTATE Raw Value',
        zShare.ZPUBLICPERMISSION AS 'zShare-ZPUBLICPERMISSION Raw Value',
        zSharePartic.ZACCEPTANCESTATUS AS 'zSharePartic-ZACCEPTANCESTATUS Raw Value',
        zSharePartic.ZUSERIDENTIFIER AS 'zSharePartic-User ID',
        zSharePartic.Z_PK AS 'zSharePartic-zPK',
        zSharePartic.ZEMAILADDRESS AS 'zSharePartic-Email Address',
        zSharePartic.ZPHONENUMBER AS 'zSharePartic-Phone Number',
        zSharePartic.ZISCURRENTUSER AS 'zSharePartic-ZISCURRENTUSER Raw Value',
        zSharePartic.ZROLE AS 'zSharePartic-ZROLE Raw Value',
        zSharePartic.ZPERMISSION AS 'zSharePartic-ZPERMISSION Raw Value',
        zShare.ZSHOULDNOTIFYONUPLOADCOMPLETION AS 'zShare-ZSHOULDNOTIFYONUPLOADCOMPLETION Raw Value',
        zShare.ZSHOULDIGNOREBUDGETS AS 'zShare-ZSHOULDIGNOREBUDGETS Raw Value',
        zShare.ZTRASHEDSTATE AS 'zShare-ZTRASHEDSTATE Raw Value',
        zShare.ZCLOUDDELETESTATE AS 'zShare-ZCLOUDDELETESTATE Raw Value',
        zShare.Z_ENT AS 'zShare-Z_ENT Raw Value'
        FROM ZASSET zAsset
            LEFT JOIN ZADDITIONALASSETATTRIBUTES zAddAssetAttr ON zAddAssetAttr.Z_PK = zAsset.ZADDITIONALATTRIBUTES
            LEFT JOIN ZEXTENDEDATTRIBUTES zExtAttr ON zExtAttr.Z_PK = zAsset.ZEXTENDEDATTRIBUTES
            LEFT JOIN ZCLOUDMASTER zCldMast ON zAsset.ZMASTER = zCldMast.Z_PK
            LEFT JOIN ZSHARE zShare ON zShare.Z_PK = zAsset.ZMOMENTSHARE
            LEFT JOIN ZSHAREPARTICIPANT zSharePartic ON zSharePartic.ZSHARE = zShare.Z_PK
        WHERE zAsset.ZSAVEDASSETTYPE = 8
        ORDER BY zShare.ZCREATIONDATE
        '''

        db_records = get_sqlite_db_records(source_path, null_absent_columns(source_path, query))
        for row in db_records:
            data_list.append((row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9],
            row[10], row[11], row[12], row[13], row[14], row[15], row[16], row[17], row[18],
            row[19], row[20], row[21], row[22], row[23], row[24], row[25], row[26], row[27],
            row[28], row[29], row[30], row[31], row[32], row[33], row[34], row[35], row[36],
            row[37], row[38], row[39], row[40], row[41], row[42], row[43], row[44], row[45],
            row[46], row[47], row[48], row[49], row[50], row[51], row[52], row[53], row[54],
            row[55], row[56]))

        data_headers = (('zShare-Creation Date-0', 'datetime'),
        ('zShare-Start Date-1', 'datetime'),
        ('zShare-End Date-2', 'datetime'),
        ('zShare-Expiry Date-3', 'datetime'),
        ('zAsset-Date Created-4', 'datetime'),
        'zAsset-zPK-5',
        'zAsset-Directory-Path-6',
        'zAsset-Filename-7',
        'zAddAssetAttr- Original Filename-8',
        'zCldMast- Original Filename-9',
        'zAddAssetAttr- Syndication Identifier-SWY-Files-10',
        'zAsset-ZSYNDICATIONSTATE Raw Value-11',
        'zAsset-ZBUNDLESCOPE Raw Value-12',
        'zAddAssetAttr- Imported by Bundle Identifier-13',
        'zAddAssetAttr-Imported By Display Name-14',
        'zAsset-ZVISIBILITYSTATE Raw Value-15',
        'zAsset-ZSAVEDASSETTYPE Raw Value-16',
        'zAddAssetAttr-ZSHARETYPE Raw Value-17',
        ('zAsset- SortToken -CameraRoll-18', 'datetime'),
        ('zAsset-Added Date-19', 'datetime'),
        ('zCldMast-Creation Date-20', 'datetime'),
        'zAddAssetAttr-Time Zone Name-21',
        'zAddAssetAttr-EXIF-String-22',
        ('zAsset-Modification Date-23', 'datetime'),
        ('zAsset-Last Shared Date-24', 'datetime'),
        ('zAsset-Trashed Date-25', 'datetime'),
        'zAddAssetAttr-zPK-26',
        'zAsset-UUID = store.cloudphotodb-27',
        'zAddAssetAttr-Master Fingerprint-28',
        'zShare-UUID-29',
        'zShare-Originating Scope ID-30',
        'zShare-ZSTATUS Raw Value-31',
        'zShare-ZSCOPETYPE Raw Value-32',
        'zShare-Asset Count-CMM-33',
        'zShare-Force Sync Attempted-CMM-34',
        'zShare-Photos Count-CMM-35',
        'zShare-Uploaded Photos Count-CMM-36',
        'zShare-Videos Count-CMM-37',
        'zShare-Uploaded Videos Count-CMM-38',
        'zShare-Scope ID-39',
        'zShare-Title-SPL-40',
        'zShare-Share URL-41',
        'zShare-ZLOCALPUBLISHSTATE Raw Value-42',
        'zShare-ZPUBLICPERMISSION Raw Value-43',
        'zSharePartic-ZACCEPTANCESTATUS Raw Value-44',
        'zSharePartic-User ID-45',
        'zSharePartic-zPK-46',
        'zSharePartic-Email Address-47',
        'zSharePartic-Phone Number-48',
        'zSharePartic-ZISCURRENTUSER Raw Value-49',
        'zSharePartic-ZROLE Raw Value-50',
        'zSharePartic-ZPERMISSION Raw Value-51',
        'zShare-ZSHOULDNOTIFYONUPLOADCOMPLETION Raw Value-52',
        'zShare-ZSHOULDIGNOREBUDGETS Raw Value-53',
        'zShare-ZTRASHEDSTATE Raw Value-54',
        'zShare-ZCLOUDDELETESTATE Raw Value-55',
        'zShare-Z_ENT Raw Value-56')
# data_list = get_sqlite_db_records(source_path, null_absent_columns(source_path, query))

        return data_headers, data_list, source_path

    elif (version.parse(iosversion) >= version.parse("16")) & (version.parse(iosversion) < version.parse("17")):
        source_path = get_file_path(files_found,"Photos.sqlite")
        if source_path is None or not os.path.exists(source_path):
            logfunc(f"Photos.sqlite not found for iOS version {iosversion}")
            return (), [], source_path
        data_list = []

        query = '''
        SELECT
        DateTime(zShare.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Creation Date',
        DateTime(zShare.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Start Date',
        DateTime(zShare.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'zShare-End Date',
        DateTime(zShare.ZEXPIRYDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Expiry Date',
        DateTime(zAsset.ZDATECREATED + 978307200, 'UNIXEPOCH') AS 'zAsset-Date Created',
        zAsset.Z_PK AS 'zAsset-zPK',
        zAsset.ZDIRECTORY AS 'zAsset-Directory-Path',
        zAsset.ZFILENAME AS 'zAsset-Filename',
        zAddAssetAttr.ZORIGINALFILENAME AS 'zAddAssetAttr- Original Filename',
        zCldMast.ZORIGINALFILENAME AS 'zCldMast- Original Filename',
        zAddAssetAttr.ZSYNDICATIONIDENTIFIER AS 'zAddAssetAttr- Syndication Identifier-SWY-Files',
        zAsset.ZSYNDICATIONSTATE AS 'zAsset-ZSYNDICATIONSTATE Raw Value',
        zAsset.ZBUNDLESCOPE AS 'zAsset-ZBUNDLESCOPE Raw Value',
        zAddAssetAttr.ZIMPORTEDBY AS 'zAddAssetAttr-ZIMPORTEDBY Raw Value',
        zExtAttr.ZCAMERAMAKE AS 'zExtAttr-Camera Make',
        zExtAttr.ZCAMERAMODEL AS 'zExtAttr-Camera Model',
        zAddAssetAttr.ZIMPORTEDBYBUNDLEIDENTIFIER AS 'zAddAssetAttr- Imported by Bundle Identifier',
        zAddAssetAttr.ZIMPORTEDBYDISPLAYNAME AS 'zAddAssetAttr- Imported By Display Name',
        zAsset.ZVISIBILITYSTATE AS 'zAsset-ZVISIBILITYSTATE Raw Value',
        zAsset.ZSAVEDASSETTYPE AS 'zAsset-ZSAVEDASSETTYPE Raw Value',
        zAddAssetAttr.ZSHARETYPE AS 'zAddAssetAttr-ZSHARETYPE Raw Value',
        DateTime(zAsset.ZSORTTOKEN + 978307200, 'UNIXEPOCH') AS 'zAsset- SortToken -CameraRoll',
        DateTime(zAsset.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Added Date',        
        DateTime(zCldMast.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'zCldMast-Creation Date',
        zAddAssetAttr.ZTIMEZONENAME AS 'zAddAssetAttr-Time Zone Name',
        zAddAssetAttr.ZEXIFTIMESTAMPSTRING AS 'zAddAssetAttr-EXIF-String',
        DateTime(zAsset.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Modification Date',
        DateTime(zAsset.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Last Shared Date',
        zAsset.ZHIDDEN AS 'zAsset-ZHIDDEN Raw Value',
        zAsset.ZAVALANCHEPICKTYPE AS 'zAsset-ZAVALANCHEPICKTYPE Raw Value',
        zAddAssetAttr.ZCLOUDAVALANCHEPICKTYPE AS 'zAddAssetAttr-ZCLOUDAVALANCHEPICKTYPE Raw Value',
        zAsset.ZTRASHEDSTATE AS 'zAsset-ZTRASHEDSTATE Raw Value',
        DateTime(zAsset.ZTRASHEDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Trashed Date',
        zAsset.ZTRASHEDBYPARTICIPANT AS 'zAsset-Trashed by Participant= zShareParticipant_zPK',
        zAddAssetAttr.Z_PK AS 'zAddAssetAttr-zPK',
        zAsset.ZUUID AS 'zAsset-UUID = store.cloudphotodb',
        zAddAssetAttr.ZMASTERFINGERPRINT AS 'zAddAssetAttr-Master Fingerprint',
        zAddAssetAttr.ZADJUSTEDFINGERPRINT AS 'zAddAssetAttr.Adjusted Fingerprint',
        zShare.ZUUID AS 'zShare-UUID',
        zShare.ZORIGINATINGSCOPEIDENTIFIER AS 'zShare-Originating Scope ID',
        zSharePartic.Z54_SHARE AS 'zSharePartic-Z54_SHARE Raw Value',
        zShare.ZSTATUS AS 'zShare-ZSTATUS Raw Value',
        zShare.ZSCOPETYPE AS 'zShare-ZSCOPETYPE Raw Value',
        zShare.ZASSETCOUNT AS 'zShare-Asset Count-CMM',
        zShare.ZFORCESYNCATTEMPTED AS 'zShare-Force Sync Attempted-CMM',  
        zShare.ZPHOTOSCOUNT AS 'zShare-Photos Count-CMM',
        zShare.ZUPLOADEDPHOTOSCOUNT AS 'zShare-Uploaded Photos Count-CMM',
        zShare.ZVIDEOSCOUNT AS 'zShare-Videos Count-CMM',
        zShare.ZUPLOADEDVIDEOSCOUNT AS 'zShare-Uploaded Videos Count-CMM',  
        zShare.ZSCOPEIDENTIFIER AS 'zShare-Scope ID',
        zShare.ZTITLE AS 'zShare-Title-SPL',
        zShare.ZSHAREURL AS 'zShare-Share URL',
        zShare.ZLOCALPUBLISHSTATE AS 'zShare-ZLOCALPUBLISHSTATE Raw Value',
        zShare.ZPUBLICPERMISSION AS 'zShare-ZPUBLICPERMISSION Raw Value',
        zShare.ZCLOUDLOCALSTATE AS 'zShare-ZCLOUDLOCALSTATE Raw Value',
        zShare.ZSCOPESYNCINGSTATE AS 'zShare-ZSCOPESYNCINGSTATE Raw Value',
        zShare.ZAUTOSHAREPOLICY AS 'zShare-ZAUTOSHAREPOLICY Raw Value',
        zSharePartic.ZACCEPTANCESTATUS AS 'zSharePartic-ZACCEPTANCESTATUS Raw Value',
        zSharePartic.ZUSERIDENTIFIER AS 'zSharePartic-User ID',
        zSharePartic.Z_PK AS 'zSharePartic-zPK',
        zSharePartic.ZEMAILADDRESS AS 'zSharePartic-Email Address',
        zSharePartic.ZPHONENUMBER AS 'zSharePartic-Phone Number',
        zSharePartic.ZPARTICIPANTID AS 'zSharePartic-Participant ID',
        zSharePartic.ZUUID AS 'zSharePartic-UUID',  
        zSharePartic.ZISCURRENTUSER AS 'zSharePartic-ZISCURRENTUSER Raw Value',
        zSharePartic.ZROLE AS 'zSharePartic-ZROLE Raw Value',
        zSharePartic.ZPERMISSION AS 'zSharePartic-ZPERMISSION Raw Value',
        zShare.ZPARTICIPANTCLOUDUPDATESTATE AS 'zShare-ZPARTICIPANTCLOUDUPDATESTATE Raw Value',
        zShare.ZPREVIEWSTATE AS 'zShare-ZPREVIEWSTATE Raw Value',
        zShare.ZSHOULDNOTIFYONUPLOADCOMPLETION AS 'zShare-ZSHOULDNOTIFYONUPLOADCOMPLETION Raw Value',
        zShare.ZSHOULDIGNOREBUDGETS AS 'zShare-ZSHOULDIGNOREBUDGETS Raw Value',
        zShare.ZTRASHEDSTATE AS 'zShare-ZTRASHEDSTATE Raw Value',
        zShare.ZCLOUDDELETESTATE AS 'zShare-ZCLOUDDELETESTATE Raw Value',
        DateTime(zShare.ZTRASHEDDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Trashed Date',
        DateTime(zShare.ZLASTPARTICIPANTASSETTRASHNOTIFICATIONDATE + 978307200, 'UNIXEPOCH') AS
         'zShare-LastParticipant Asset Trash Notification Date',
        DateTime(zShare.ZLASTPARTICIPANTASSETTRASHNOTIFICATIONVIEWEDDATE + 978307200, 'UNIXEPOCH') AS
         'zShare-Last Participant Asset Trash Notification View Date',
        zShare.Z_ENT AS 'zShare-Z_ENT Raw Value'
        FROM ZASSET zAsset
            LEFT JOIN ZADDITIONALASSETATTRIBUTES zAddAssetAttr ON zAddAssetAttr.Z_PK = zAsset.ZADDITIONALATTRIBUTES
            LEFT JOIN ZEXTENDEDATTRIBUTES zExtAttr ON zExtAttr.Z_PK = zAsset.ZEXTENDEDATTRIBUTES
            LEFT JOIN ZCLOUDMASTER zCldMast ON zAsset.ZMASTER = zCldMast.Z_PK
            LEFT JOIN ZSHARE zShare ON zShare.Z_PK = zAsset.ZMOMENTSHARE
            LEFT JOIN ZSHAREPARTICIPANT zSharePartic ON zSharePartic.ZSHARE = zShare.Z_PK
        WHERE zAsset.ZSAVEDASSETTYPE = 8
        ORDER BY zShare.ZCREATIONDATE
        '''

        db_records = get_sqlite_db_records(source_path, null_absent_columns(source_path, query))
        for row in db_records:
            data_list.append((row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9],
            row[10], row[11], row[12], row[13], row[14], row[15], row[16], row[17], row[18],
            row[19], row[20], row[21], row[22], row[23], row[24], row[25], row[26], row[27],
            row[28], row[29], row[30], row[31], row[32], row[33], row[34], row[35], row[36],
            row[37], row[38], row[39], row[40], row[41], row[42], row[43], row[44], row[45],
            row[46], row[47], row[48], row[49], row[50], row[51], row[52], row[53], row[54],
            row[55], row[56], row[57], row[58], row[59], row[60], row[61], row[62], row[63],
            row[64], row[65], row[66], row[67], row[68], row[69], row[70], row[71], row[72],
            row[73], row[74], row[75], row[76]))

        data_headers = (('zShare-Creation Date-0', 'datetime'),
        ('zShare-Start Date-1', 'datetime'),
        ('zShare-End Date-2', 'datetime'),
        ('zShare-Expiry Date-3', 'datetime'),
        ('zAsset-Date Created-4', 'datetime'),
        'zAsset-zPK-5',
        'zAsset-Directory-Path-6',
        'zAsset-Filename-7',
        'zAddAssetAttr- Original Filename-8',
        'zCldMast- Original Filename-9',
        'zAddAssetAttr- Syndication Identifier-SWY-Files-10',
        'zAsset-ZSYNDICATIONSTATE Raw Value-11',
        'zAsset-ZBUNDLESCOPE Raw Value-12',
        'zAddAssetAttr-ZIMPORTEDBY Raw Value-13',
        'zExtAttr-Camera Make-14',
        'zExtAttr-Camera Model-15',
        'zAddAssetAttr- Imported by Bundle Identifier-16',
        'zAddAssetAttr- Imported By Display Name-17',
        'zAsset-ZVISIBILITYSTATE Raw Value-18',
        'zAsset-ZSAVEDASSETTYPE Raw Value-19',
        'zAddAssetAttr-ZSHARETYPE Raw Value-20',
        ('zAsset- SortToken -CameraRoll-21', 'datetime'),
        ('zAsset-Added Date-22', 'datetime'),
        ('zCldMast-Creation Date-23', 'datetime'),
        'zAddAssetAttr-Time Zone Name-24',
        'zAddAssetAttr-EXIF-String-25',
        ('zAsset-Modification Date-26', 'datetime'),
        ('zAsset-Last Shared Date-27', 'datetime'),
        'zAsset-ZHIDDEN Raw Value-28',
        'zAsset-ZAVALANCHEPICKTYPE Raw Value-29',
        'zAddAssetAttr-ZCLOUDAVALANCHEPICKTYPE Raw Value-30',
        'zAsset-ZTRASHEDSTATE Raw Value-31',
        ('zAsset-Trashed Date-32', 'datetime'),
        'zAsset-Trashed by Participant= zShareParticipant_zPK-33',
        'zAddAssetAttr-zPK-34',
        'zAsset-UUID = store.cloudphotodb-35',
        'zAddAssetAttr-Master Fingerprint-36',
        'zAddAssetAttr.Adjusted Fingerprint-37',
        'zShare-UUID-38',
        'zShare-Originating Scope ID-39',
        'zSharePartic-Z54_SHARE Raw Value-40',
        'zShare-ZSTATUS Raw Value-41',
        'zShare-ZSCOPETYPE Raw Value-42',
        'zShare-Asset Count-CMM-43',
        'zShare-Force Sync Attempted-CMM-44',
        'zShare-Photos Count-CMM-45',
        'zShare-Uploaded Photos Count-CMM-46',
        'zShare-Videos Count-CMM-47',
        'zShare-Uploaded Videos Count-CMM-48',
        'zShare-Scope ID-49',
        'zShare-Title-SPL-50',
        'zShare-Share URL-51',
        'zShare-ZLOCALPUBLISHSTATE Raw Value-52',
        'zShare-ZPUBLICPERMISSION Raw Value-53',
        'zShare-ZCLOUDLOCALSTATE Raw Value-54',
        'zShare-ZSCOPESYNCINGSTATE Raw Value-55',
        'zShare-ZAUTOSHAREPOLICY Raw Value-56',
        'zSharePartic-ZACCEPTANCESTATUS Raw Value-57',
        'zSharePartic-User ID-58',
        'zSharePartic-zPK-59',
        'zSharePartic-Email Address-60',
        'zSharePartic-Phone Number-61',
        'zSharePartic-Participant ID-62',
        'zSharePartic-UUID-63',
        'zSharePartic-ZISCURRENTUSER Raw Value-64',
        'zSharePartic-ZROLE Raw Value-65',
        'zSharePartic-ZPERMISSION Raw Value-66',
        'zShare-ZPARTICIPANTCLOUDUPDATESTATE Raw Value-67',
        'zShare-ZPREVIEWSTATE Raw Value-68',
        'zShare-ZSHOULDNOTIFYONUPLOADCOMPLETION Raw Value-69',
        'zShare-ZSHOULDIGNOREBUDGETS Raw Value-70',
        'zShare-ZTRASHEDSTATE Raw Value-71',
        'zShare-ZCLOUDDELETESTATE Raw Value-72',
        ('zShare-Trashed Date-73', 'datetime'),
        ('zShare-LastParticipant Asset Trash Notification Date-74', 'datetime'),
        ('zShare-Last Participant Asset Trash Notification View Date-75', 'datetime'),
        'zShare-Z_ENT Raw Value-76')
# data_list = get_sqlite_db_records(source_path, null_absent_columns(source_path, query))

        return data_headers, data_list, source_path

    elif (version.parse(iosversion) >= version.parse("17")) & (version.parse(iosversion) < version.parse("17.6")):
        source_path = get_file_path(files_found,"Photos.sqlite")
        if source_path is None or not os.path.exists(source_path):
            logfunc(f"Photos.sqlite not found for iOS version {iosversion}")
            return (), [], source_path
        data_list = []

        query = '''
        SELECT
        DateTime(zShare.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Creation Date',
        DateTime(zShare.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Start Date',
        DateTime(zShare.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'zShare-End Date',
        DateTime(zShare.ZEXPIRYDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Expiry Date',
        DateTime(zAsset.ZDATECREATED + 978307200, 'UNIXEPOCH') AS 'zAsset-Date Created',
        zAsset.Z_PK AS 'zAsset-zPK',
        zAsset.ZDIRECTORY AS 'zAsset-Directory-Path',
        zAsset.ZFILENAME AS 'zAsset-Filename',
        zAddAssetAttr.ZORIGINALFILENAME AS 'zAddAssetAttr- Original Filename',
        zCldMast.ZORIGINALFILENAME AS 'zCldMast- Original Filename',
        zAddAssetAttr.ZSYNDICATIONIDENTIFIER AS 'zAddAssetAttr- Syndication Identifier-SWY-Files',
        zAsset.ZSYNDICATIONSTATE AS 'zAsset-ZSYNDICATIONSTATE Raw Value',
        zAsset.ZBUNDLESCOPE AS 'zAsset-ZBUNDLESCOPE Raw Value',
        zAddAssetAttr.ZIMPORTEDBY AS 'zAddAssetAttr-ZIMPORTEDBY Raw Value',
        zExtAttr.ZCAMERAMAKE AS 'zExtAttr-Camera Make',
        zExtAttr.ZCAMERAMODEL AS 'zExtAttr-Camera Model',
        zAddAssetAttr.ZIMPORTEDBYBUNDLEIDENTIFIER AS 'zAddAssetAttr- Imported by Bundle Identifier',
        zAddAssetAttr.ZIMPORTEDBYDISPLAYNAME AS 'zAddAssetAttr- Imported By Display Name',
        zAsset.ZVISIBILITYSTATE AS 'zAsset-ZVISIBILITYSTATE Raw Value',
        zAsset.ZSAVEDASSETTYPE AS 'zAsset-ZSAVEDASSETTYPE Raw Value',
        zAddAssetAttr.ZSHARETYPE AS 'zAddAssetAttr-ZSHARETYPE Raw Value',
        zAsset.ZACTIVELIBRARYSCOPEPARTICIPATIONSTATE AS 'zAsset-ZACTIVELIBRARYSCOPEPARTICIPATIONSTATE Raw Value',
        DateTime(zAsset.ZSORTTOKEN + 978307200, 'UNIXEPOCH') AS 'zAsset- SortToken -CameraRoll',
        DateTime(zAsset.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Added Date',        
        DateTime(zCldMast.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'zCldMast-Creation Date',
        zAddAssetAttr.ZTIMEZONENAME AS 'zAddAssetAttr-Time Zone Name',
        zAddAssetAttr.ZEXIFTIMESTAMPSTRING AS 'zAddAssetAttr-EXIF-String',
        DateTime(zAsset.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Modification Date',
        DateTime(zAsset.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Last Shared Date',
        zAsset.ZHIDDEN AS 'zAsset-ZHIDDEN Raw Value',
        zAsset.ZAVALANCHEPICKTYPE AS 'zAsset-ZAVALANCHEPICKTYPE Raw Value',
        zAddAssetAttr.ZCLOUDAVALANCHEPICKTYPE AS 'zAddAssetAttr-ZCLOUDAVALANCHEPICKTYPE Raw Value',
        zAsset.ZTRASHEDSTATE AS 'zAsset-ZTRASHEDSTATE Raw Value',
        DateTime(zAsset.ZTRASHEDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Trashed Date',
        zAsset.ZTRASHEDBYPARTICIPANT AS 'zAsset-Trashed by Participant= zShareParticipant_zPK',
        zAddAssetAttr.Z_PK AS 'zAddAssetAttr-zPK',
        zAsset.ZUUID AS 'zAsset-UUID = store.cloudphotodb',
        zAddAssetAttr.ZMASTERFINGERPRINT AS 'zAddAssetAttr-Master Fingerprint',
        zAddAssetAttr.ZADJUSTEDFINGERPRINT AS 'zAddAssetAttr.Adjusted Fingerprint',
        zShare.ZUUID AS 'zShare-UUID',
        zShare.ZORIGINATINGSCOPEIDENTIFIER AS 'zShare-Originating Scope ID',
        zSharePartic.Z54_SHARE AS 'zSharePartic-Z54_SHARE Raw Value',
        zShare.ZSTATUS AS 'zShare-ZSTATUS Raw Value',
        zShare.ZSCOPETYPE AS 'zShare-ZSCOPETYPE Raw Value',
        zShare.ZASSETCOUNT AS 'zShare-Asset Count-CMM',
        zShare.ZFORCESYNCATTEMPTED AS 'zShare-Force Sync Attempted-CMM',  
        zShare.ZPHOTOSCOUNT AS 'zShare-Photos Count-CMM',
        zShare.ZUPLOADEDPHOTOSCOUNT AS 'zShare-Uploaded Photos Count-CMM',
        zShare.ZVIDEOSCOUNT AS 'zShare-Videos Count-CMM',
        zShare.ZUPLOADEDVIDEOSCOUNT AS 'zShare-Uploaded Videos Count-CMM',  
        zShare.ZSCOPEIDENTIFIER AS 'zShare-Scope ID',
        zShare.ZTITLE AS 'zShare-Title-SPL',
        zShare.ZSHAREURL AS 'zShare-Share URL',
        zShare.ZLOCALPUBLISHSTATE AS 'zShare-ZLOCALPUBLISHSTATE Raw Value',
        zShare.ZPUBLICPERMISSION AS 'zShare-ZPUBLICPERMISSION Raw Value',
        zShare.ZCLOUDLOCALSTATE AS 'zShare-ZCLOUDLOCALSTATE Raw Value',
        zShare.ZSCOPESYNCINGSTATE AS 'zShare-ZSCOPESYNCINGSTATE Raw Value',
        zShare.ZAUTOSHAREPOLICY AS 'zShare-ZAUTOSHAREPOLICY Raw Value',
        zSharePartic.ZACCEPTANCESTATUS AS 'zSharePartic-ZACCEPTANCESTATUS Raw Value',
        zSharePartic.ZUSERIDENTIFIER AS 'zSharePartic-User ID',
        zSharePartic.Z_PK AS 'zSharePartic-zPK',
        zSharePartic.ZEMAILADDRESS AS 'zSharePartic-Email Address',
        zSharePartic.ZPHONENUMBER AS 'zSharePartic-Phone Number',
        zSharePartic.ZPARTICIPANTID AS 'zSharePartic-Participant ID',
        zSharePartic.ZUUID AS 'zSharePartic-UUID',  
        zSharePartic.ZISCURRENTUSER AS 'zSharePartic-ZISCURRENTUSER Raw Value',
        zSharePartic.ZROLE AS 'zSharePartic-ZROLE Raw Value',
        zSharePartic.ZPERMISSION AS 'zSharePartic-ZPERMISSION Raw Value',
        zShare.ZPARTICIPANTCLOUDUPDATESTATE AS 'zShare-ZPARTICIPANTCLOUDUPDATESTATE Raw Value',
        zSharePartic.ZEXITSTATE AS 'zSharePartic-ZEXITSTATE Raw Value',
        zShare.ZPREVIEWSTATE AS 'zShare-ZPREVIEWSTATE Raw Value',
        zShare.ZSHOULDNOTIFYONUPLOADCOMPLETION AS 'zShare-ZSHOULDNOTIFYONUPLOADCOMPLETION Raw Value',
        zShare.ZSHOULDIGNOREBUDGETS AS 'zShare-ZSHOULDIGNOREBUDGETS Raw Value',
        zShare.ZEXITSOURCE AS 'zShare-ZEXITSOURCE Raw Value',
        zShare.ZEXITSTATE AS 'zShare-ZEXITSTATE Raw Value',
        zShare.ZEXITTYPE AS 'zShare-ZEXITTYPE Raw Value',
        zShare.ZTRASHEDSTATE AS 'zShare-ZTRASHEDSTATE Raw Value',
        zShare.ZCLOUDDELETESTATE AS 'zShare-ZCLOUDDELETESTATE Raw Value',
        DateTime(zShare.ZTRASHEDDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Trashed Date',
        DateTime(zShare.ZLASTPARTICIPANTASSETTRASHNOTIFICATIONDATE + 978307200, 'UNIXEPOCH') AS
         'zShare-LastParticipant Asset Trash Notification Date',
        DateTime(zShare.ZLASTPARTICIPANTASSETTRASHNOTIFICATIONVIEWEDDATE + 978307200, 'UNIXEPOCH') AS
         'zShare-Last Participant Asset Trash Notification View Date',
        zShare.Z_ENT AS 'zShare-Z_ENT Raw Value'
        FROM ZASSET zAsset
            LEFT JOIN ZADDITIONALASSETATTRIBUTES zAddAssetAttr ON zAddAssetAttr.Z_PK = zAsset.ZADDITIONALATTRIBUTES
            LEFT JOIN ZEXTENDEDATTRIBUTES zExtAttr ON zExtAttr.Z_PK = zAsset.ZEXTENDEDATTRIBUTES
            LEFT JOIN ZCLOUDMASTER zCldMast ON zAsset.ZMASTER = zCldMast.Z_PK
            LEFT JOIN ZSHARE zShare ON zShare.Z_PK = zAsset.ZMOMENTSHARE
            LEFT JOIN ZSHAREPARTICIPANT zSharePartic ON zSharePartic.ZSHARE = zShare.Z_PK
        WHERE zAsset.ZSAVEDASSETTYPE = 8
        ORDER BY zShare.ZCREATIONDATE
        '''

        db_records = get_sqlite_db_records(source_path, null_absent_columns(source_path, query))
        for row in db_records:
            data_list.append((row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9],
            row[10], row[11], row[12], row[13], row[14], row[15], row[16], row[17], row[18],
            row[19], row[20], row[21], row[22], row[23], row[24], row[25], row[26], row[27],
            row[28], row[29], row[30], row[31], row[32], row[33], row[34], row[35], row[36],
            row[37], row[38], row[39], row[40], row[41], row[42], row[43], row[44], row[45],
            row[46], row[47], row[48], row[49], row[50], row[51], row[52], row[53], row[54],
            row[55], row[56], row[57], row[58], row[59], row[60], row[61], row[62], row[63],
            row[64], row[65], row[66], row[67], row[68], row[69], row[70], row[71], row[72],
            row[73], row[74], row[75], row[76], row[77], row[78], row[79], row[80], row[81]))

        data_headers = (('zShare-Creation Date-0', 'datetime'),
        ('zShare-Start Date-1', 'datetime'),
        ('zShare-End Date-2', 'datetime'),
        ('zShare-Expiry Date-3', 'datetime'),
        ('zAsset-Date Created-4', 'datetime'),
        'zAsset-zPK-5',
        'zAsset-Directory-Path-6',
        'zAsset-Filename-7',
        'zAddAssetAttr- Original Filename-8',
        'zCldMast- Original Filename-9',
        'zAddAssetAttr- Syndication Identifier-SWY-Files-10',
        'zAsset-ZSYNDICATIONSTATE Raw Value-11',
        'zAsset-ZBUNDLESCOPE Raw Value-12',
        'zAddAssetAttr-ZIMPORTEDBY Raw Value-13',
        'zExtAttr-Camera Make-14',
        'zExtAttr-Camera Model-15',
        'zAddAssetAttr- Imported by Bundle Identifier-16',
        'zAddAssetAttr- Imported By Display Name-17',
        'zAsset-ZVISIBILITYSTATE Raw Value-18',
        'zAsset-ZSAVEDASSETTYPE Raw Value-19',
        'zAddAssetAttr-ZSHARETYPE Raw Value-20',
        'zAsset-ZACTIVELIBRARYSCOPEPARTICIPATIONSTATE Raw Value-21',
        ('zAsset- SortToken -CameraRoll-22', 'datetime'),
        ('zAsset-Added Date-23', 'datetime'),
        ('zCldMast-Creation Date-24', 'datetime'),
        'zAddAssetAttr-Time Zone Name-25',
        'zAddAssetAttr-EXIF-String-26',
        ('zAsset-Modification Date-27', 'datetime'),
        ('zAsset-Last Shared Date-28', 'datetime'),
        'zAsset-ZHIDDEN Raw Value-29',
        'zAsset-ZAVALANCHEPICKTYPE Raw Value-30',
        'zAddAssetAttr-ZCLOUDAVALANCHEPICKTYPE Raw Value-31',
        'zAsset-ZTRASHEDSTATE Raw Value-32',
        ('zAsset-Trashed Date-33', 'datetime'),
        'zAsset-Trashed by Participant= zShareParticipant_zPK-34',
        'zAddAssetAttr-zPK-35',
        'zAsset-UUID = store.cloudphotodb-36',
        'zAddAssetAttr-Master Fingerprint-37',
        'zAddAssetAttr.Adjusted Fingerprint-38',
        'zShare-UUID-39',
        'zShare-Originating Scope ID-40',
        'zSharePartic-Z54_SHARE Raw Value-41',
        'zShare-ZSTATUS Raw Value-42',
        'zShare-ZSCOPETYPE Raw Value-43',
        'zShare-Asset Count-CMM-44',
        'zShare-Force Sync Attempted-CMM-45',
        'zShare-Photos Count-CMM-46',
        'zShare-Uploaded Photos Count-CMM-47',
        'zShare-Videos Count-CMM-48',
        'zShare-Uploaded Videos Count-CMM-49',
        'zShare-Scope ID-50',
        'zShare-Title-SPL-51',
        'zShare-Share URL-52',
        'zShare-ZLOCALPUBLISHSTATE Raw Value-53',
        'zShare-ZPUBLICPERMISSION Raw Value-54',
        'zShare-ZCLOUDLOCALSTATE Raw Value-55',
        'zShare-ZSCOPESYNCINGSTATE Raw Value-56',
        'zShare-ZAUTOSHAREPOLICY Raw Value-57',
        'zSharePartic-ZACCEPTANCESTATUS Raw Value-58',
        'zSharePartic-User ID-59',
        'zSharePartic-zPK-60',
        'zSharePartic-Email Address-61',
        'zSharePartic-Phone Number-62',
        'zSharePartic-Participant ID-63',
        'zSharePartic-UUID-64',
        'zSharePartic-ZISCURRENTUSER Raw Value-65',
        'zSharePartic-ZROLE Raw Value-66',
        'zSharePartic-ZPERMISSION Raw Value-67',
        'zShare-ZPARTICIPANTCLOUDUPDATESTATE Raw Value-68',
        'zSharePartic-ZEXITSTATE Raw Value-69',
        'zShare-ZPREVIEWSTATE Raw Value-70',
        'zShare-ZSHOULDNOTIFYONUPLOADCOMPLETION Raw Value-71',
        'zShare-ZSHOULDIGNOREBUDGETS Raw Value-72',
        'zShare-ZEXITSOURCE Raw Value-73',
        'zShare-ZEXITSTATE Raw Value-74',
        'zShare-ZEXITTYPE Raw Value-75',
        'zShare-ZTRASHEDSTATE Raw Value-76',
        'zShare-ZCLOUDDELETESTATE Raw Value-77',
        ('zShare-Trashed Date-78', 'datetime'),
        ('zShare-LastParticipant Asset Trash Notification Date-79', 'datetime'),
        ('zShare-Last Participant Asset Trash Notification View Date-80', 'datetime'),
        'zShare-Z_ENT Raw Value-81')
# data_list = get_sqlite_db_records(source_path, null_absent_columns(source_path, query))

        return data_headers, data_list, source_path

    elif (version.parse(iosversion) >= version.parse("17.6")) & (version.parse(iosversion) < version.parse("18")):
        source_path = get_file_path(files_found,"Photos.sqlite")
        if source_path is None or not os.path.exists(source_path):
            logfunc(f"Photos.sqlite not found for iOS version {iosversion}")
            return (), [], source_path
        data_list = []

        query = '''
        SELECT
        DateTime(zShare.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Creation Date',
        DateTime(zShare.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Start Date',
        DateTime(zShare.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'zShare-End Date',
        DateTime(zShare.ZEXPIRYDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Expiry Date',
        DateTime(zAsset.ZDATECREATED + 978307200, 'UNIXEPOCH') AS 'zAsset-Date Created',
        zAsset.Z_PK AS 'zAsset-zPK',
        zAsset.ZDIRECTORY AS 'zAsset-Directory-Path',
        zAsset.ZFILENAME AS 'zAsset-Filename',
        zAddAssetAttr.ZORIGINALFILENAME AS 'zAddAssetAttr- Original Filename',
        zCldMast.ZORIGINALFILENAME AS 'zCldMast- Original Filename',
        zAddAssetAttr.ZSYNDICATIONIDENTIFIER AS 'zAddAssetAttr- Syndication Identifier-SWY-Files',
        zAsset.ZSYNDICATIONSTATE AS 'zAsset-ZSYNDICATIONSTATE Raw Value',
        zAsset.ZBUNDLESCOPE AS 'zAsset-ZBUNDLESCOPE Raw Value',
        zAddAssetAttr.ZIMPORTEDBY AS 'zAddAssetAttr-ZIMPORTEDBY Raw Value',
        zExtAttr.ZCAMERAMAKE AS 'zExtAttr-Camera Make',
        zExtAttr.ZCAMERAMODEL AS 'zExtAttr-Camera Model',
        zAddAssetAttr.ZIMPORTEDBYBUNDLEIDENTIFIER AS 'zAddAssetAttr- Imported by Bundle Identifier',
        zAddAssetAttr.ZIMPORTEDBYDISPLAYNAME AS 'zAddAssetAttr- Imported By Display Name',
        zAsset.ZVISIBILITYSTATE AS 'zAsset-ZVISIBILITYSTATE Raw Value',
        zAsset.ZSAVEDASSETTYPE AS 'zAsset-ZSAVEDASSETTYPE Raw Value',
        zAddAssetAttr.ZSHARETYPE AS 'zAddAssetAttr-ZSHARETYPE Raw Value',
        zAsset.ZACTIVELIBRARYSCOPEPARTICIPATIONSTATE AS 'zAsset-ZACTIVELIBRARYSCOPEPARTICIPATIONSTATE Raw Value',
        DateTime(zAsset.ZSORTTOKEN + 978307200, 'UNIXEPOCH') AS 'zAsset- SortToken -CameraRoll',
        DateTime(zAsset.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Added Date',        
        DateTime(zCldMast.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'zCldMast-Creation Date',
        zAddAssetAttr.ZTIMEZONENAME AS 'zAddAssetAttr-Time Zone Name',
        zAddAssetAttr.ZEXIFTIMESTAMPSTRING AS 'zAddAssetAttr-EXIF-String',
        DateTime(zAsset.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Modification Date',
        DateTime(zAsset.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Last Shared Date',
        zAsset.ZHIDDEN AS 'zAsset-ZHIDDEN Raw Value',
        zAsset.ZAVALANCHEPICKTYPE AS 'zAsset-ZAVALANCHEPICKTYPE Raw Value',
        zAddAssetAttr.ZCLOUDAVALANCHEPICKTYPE AS 'zAddAssetAttr-ZCLOUDAVALANCHEPICKTYPE Raw Value',
        zAsset.ZTRASHEDSTATE AS 'zAsset-ZTRASHEDSTATE Raw Value',
        DateTime(zAsset.ZTRASHEDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Trashed Date',
        zAsset.ZTRASHEDBYPARTICIPANT AS 'zAsset-Trashed by Participant= zShareParticipant_zPK',
        zAddAssetAttr.Z_PK AS 'zAddAssetAttr-zPK',
        zAsset.ZUUID AS 'zAsset-UUID = store.cloudphotodb',
        zAddAssetAttr.ZMASTERFINGERPRINT AS 'zAddAssetAttr-Master Fingerprint',
        zAddAssetAttr.ZADJUSTEDFINGERPRINT AS 'zAddAssetAttr.Adjusted Fingerprint',
        zShare.ZUUID AS 'zShare-UUID',
        zShare.ZORIGINATINGSCOPEIDENTIFIER AS 'zShare-Originating Scope ID',
        zSharePartic.Z55_SHARE AS 'zSharePartic-Z55_SHARE Raw Value',
        zShare.ZSTATUS AS 'zShare-ZSTATUS Raw Value',
        zShare.ZSCOPETYPE AS 'zShare-ZSCOPETYPE Raw Value',
        zShare.ZASSETCOUNT AS 'zShare-Asset Count-CMM',
        zShare.ZFORCESYNCATTEMPTED AS 'zShare-Force Sync Attempted-CMM',  
        zShare.ZPHOTOSCOUNT AS 'zShare-Photos Count-CMM',
        zShare.ZUPLOADEDPHOTOSCOUNT AS 'zShare-Uploaded Photos Count-CMM',
        zShare.ZVIDEOSCOUNT AS 'zShare-Videos Count-CMM',
        zShare.ZUPLOADEDVIDEOSCOUNT AS 'zShare-Uploaded Videos Count-CMM',  
        zShare.ZSCOPEIDENTIFIER AS 'zShare-Scope ID',
        zShare.ZTITLE AS 'zShare-Title-SPL',
        zShare.ZSHAREURL AS 'zShare-Share URL',
        zShare.ZLOCALPUBLISHSTATE AS 'zShare-ZLOCALPUBLISHSTATE Raw Value',
        zShare.ZPUBLICPERMISSION AS 'zShare-ZPUBLICPERMISSION Raw Value',
        zShare.ZCLOUDLOCALSTATE AS 'zShare-ZCLOUDLOCALSTATE Raw Value',
        zShare.ZSCOPESYNCINGSTATE AS 'zShare-ZSCOPESYNCINGSTATE Raw Value',
        zShare.ZAUTOSHAREPOLICY AS 'zShare-ZAUTOSHAREPOLICY Raw Value',
        zSharePartic.ZACCEPTANCESTATUS AS 'zSharePartic-ZACCEPTANCESTATUS Raw Value',
        zSharePartic.ZUSERIDENTIFIER AS 'zSharePartic-User ID',
        zSharePartic.Z_PK AS 'zSharePartic-zPK',
        zSharePartic.ZEMAILADDRESS AS 'zSharePartic-Email Address',
        zSharePartic.ZPHONENUMBER AS 'zSharePartic-Phone Number',
        zSharePartic.ZPARTICIPANTID AS 'zSharePartic-Participant ID',
        zSharePartic.ZUUID AS 'zSharePartic-UUID',  
        zSharePartic.ZISCURRENTUSER AS 'zSharePartic-ZISCURRENTUSER Raw Value',
        zSharePartic.ZROLE AS 'zSharePartic-ZROLE Raw Value',
        zSharePartic.ZPERMISSION AS 'zSharePartic-ZPERMISSION Raw Value',
        zShare.ZPARTICIPANTCLOUDUPDATESTATE AS 'zShare-ZPARTICIPANTCLOUDUPDATESTATE Raw Value',
        zSharePartic.ZEXITSTATE AS 'zSharePartic-ZEXITSTATE Raw Value',
        zShare.ZPREVIEWSTATE AS 'zShare-ZPREVIEWSTATE Raw Value',
        zShare.ZSHOULDNOTIFYONUPLOADCOMPLETION AS 'zShare-ZSHOULDNOTIFYONUPLOADCOMPLETION Raw Value',
        zShare.ZSHOULDIGNOREBUDGETS AS 'zShare-ZSHOULDIGNOREBUDGETS Raw Value',
        zShare.ZEXITSOURCE AS 'zShare-ZEXITSOURCE Raw Value',
        zShare.ZEXITSTATE AS 'zShare-ZEXITSTATE Raw Value',
        zShare.ZEXITTYPE AS 'zShare-ZEXITTYPE Raw Value',
        zShare.ZTRASHEDSTATE AS 'zShare-ZTRASHEDSTATE Raw Value',
        zShare.ZCLOUDDELETESTATE AS 'zShare-ZCLOUDDELETESTATE Raw Value',
        DateTime(zShare.ZTRASHEDDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Trashed Date',
        DateTime(zShare.ZLASTPARTICIPANTASSETTRASHNOTIFICATIONDATE + 978307200, 'UNIXEPOCH') AS
         'zShare-LastParticipant Asset Trash Notification Date',
        DateTime(zShare.ZLASTPARTICIPANTASSETTRASHNOTIFICATIONVIEWEDDATE + 978307200, 'UNIXEPOCH') AS
         'zShare-Last Participant Asset Trash Notification View Date',
        zShare.Z_ENT AS 'zShare-Z_ENT Raw Value'
        FROM ZASSET zAsset
            LEFT JOIN ZADDITIONALASSETATTRIBUTES zAddAssetAttr ON zAddAssetAttr.Z_PK = zAsset.ZADDITIONALATTRIBUTES
            LEFT JOIN ZEXTENDEDATTRIBUTES zExtAttr ON zExtAttr.Z_PK = zAsset.ZEXTENDEDATTRIBUTES
            LEFT JOIN ZCLOUDMASTER zCldMast ON zAsset.ZMASTER = zCldMast.Z_PK
            LEFT JOIN ZSHARE zShare ON zShare.Z_PK = zAsset.ZMOMENTSHARE
            LEFT JOIN ZSHAREPARTICIPANT zSharePartic ON zSharePartic.ZSHARE = zShare.Z_PK
        WHERE zAsset.ZSAVEDASSETTYPE = 8
        ORDER BY zShare.ZCREATIONDATE
        '''

        db_records = get_sqlite_db_records(source_path, null_absent_columns(source_path, query))
        for row in db_records:
            data_list.append((row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9],
            row[10], row[11], row[12], row[13], row[14], row[15], row[16], row[17], row[18],
            row[19], row[20], row[21], row[22], row[23], row[24], row[25], row[26], row[27],
            row[28], row[29], row[30], row[31], row[32], row[33], row[34], row[35], row[36],
            row[37], row[38], row[39], row[40], row[41], row[42], row[43], row[44], row[45],
            row[46], row[47], row[48], row[49], row[50], row[51], row[52], row[53], row[54],
            row[55], row[56], row[57], row[58], row[59], row[60], row[61], row[62], row[63],
            row[64], row[65], row[66], row[67], row[68], row[69], row[70], row[71], row[72],
            row[73], row[74], row[75], row[76], row[77], row[78], row[79], row[80], row[81]))

        data_headers = (('zShare-Creation Date-0', 'datetime'),
        ('zShare-Start Date-1', 'datetime'),
        ('zShare-End Date-2', 'datetime'),
        ('zShare-Expiry Date-3', 'datetime'),
        ('zAsset-Date Created-4', 'datetime'),
        'zAsset-zPK-5',
        'zAsset-Directory-Path-6',
        'zAsset-Filename-7',
        'zAddAssetAttr- Original Filename-8',
        'zCldMast- Original Filename-9',
        'zAddAssetAttr- Syndication Identifier-SWY-Files-10',
        'zAsset-ZSYNDICATIONSTATE Raw Value-11',
        'zAsset-ZBUNDLESCOPE Raw Value-12',
        'zAddAssetAttr-ZIMPORTEDBY Raw Value-13',
        'zExtAttr-Camera Make-14',
        'zExtAttr-Camera Model-15',
        'zAddAssetAttr- Imported by Bundle Identifier-16',
        'zAddAssetAttr- Imported By Display Name-17',
        'zAsset-ZVISIBILITYSTATE Raw Value-18',
        'zAsset-ZSAVEDASSETTYPE Raw Value-19',
        'zAddAssetAttr-ZSHARETYPE Raw Value-20',
        'zAsset-ZACTIVELIBRARYSCOPEPARTICIPATIONSTATE Raw Value-21',
        ('zAsset- SortToken -CameraRoll-22', 'datetime'),
        ('zAsset-Added Date-23', 'datetime'),
        ('zCldMast-Creation Date-24', 'datetime'),
        'zAddAssetAttr-Time Zone Name-25',
        'zAddAssetAttr-EXIF-String-26',
        ('zAsset-Modification Date-27', 'datetime'),
        ('zAsset-Last Shared Date-28', 'datetime'),
        'zAsset-ZHIDDEN Raw Value-29',
        'zAsset-ZAVALANCHEPICKTYPE Raw Value-30',
        'zAddAssetAttr-ZCLOUDAVALANCHEPICKTYPE Raw Value-31',
        'zAsset-ZTRASHEDSTATE Raw Value-32',
        ('zAsset-Trashed Date-33', 'datetime'),
        'zAsset-Trashed by Participant= zShareParticipant_zPK-34',
        'zAddAssetAttr-zPK-35',
        'zAsset-UUID = store.cloudphotodb-36',
        'zAddAssetAttr-Master Fingerprint-37',
        'zAddAssetAttr.Adjusted Fingerprint-38',
        'zShare-UUID-39',
        'zShare-Originating Scope ID-40',
        'zSharePartic-Z55_SHARE Raw Value-41',
        'zShare-ZSTATUS Raw Value-42',
        'zShare-ZSCOPETYPE Raw Value-43',
        'zShare-Asset Count-CMM-44',
        'zShare-Force Sync Attempted-CMM-45',
        'zShare-Photos Count-CMM-46',
        'zShare-Uploaded Photos Count-CMM-47',
        'zShare-Videos Count-CMM-48',
        'zShare-Uploaded Videos Count-CMM-49',
        'zShare-Scope ID-50',
        'zShare-Title-SPL-51',
        'zShare-Share URL-52',
        'zShare-ZLOCALPUBLISHSTATE Raw Value-53',
        'zShare-ZPUBLICPERMISSION Raw Value-54',
        'zShare-ZCLOUDLOCALSTATE Raw Value-55',
        'zShare-ZSCOPESYNCINGSTATE Raw Value-56',
        'zShare-ZAUTOSHAREPOLICY Raw Value-57',
        'zSharePartic-ZACCEPTANCESTATUS Raw Value-58',
        'zSharePartic-User ID-59',
        'zSharePartic-zPK-60',
        'zSharePartic-Email Address-61',
        'zSharePartic-Phone Number-62',
        'zSharePartic-Participant ID-63',
        'zSharePartic-UUID-64',
        'zSharePartic-ZISCURRENTUSER Raw Value-65',
        'zSharePartic-ZROLE Raw Value-66',
        'zSharePartic-ZPERMISSION Raw Value-67',
        'zShare-ZPARTICIPANTCLOUDUPDATESTATE Raw Value-68',
        'zSharePartic-ZEXITSTATE Raw Value-69',
        'zShare-ZPREVIEWSTATE Raw Value-70',
        'zShare-ZSHOULDNOTIFYONUPLOADCOMPLETION Raw Value-71',
        'zShare-ZSHOULDIGNOREBUDGETS Raw Value-72',
        'zShare-ZEXITSOURCE Raw Value-73',
        'zShare-ZEXITSTATE Raw Value-74',
        'zShare-ZEXITTYPE Raw Value-75',
        'zShare-ZTRASHEDSTATE Raw Value-76',
        'zShare-ZCLOUDDELETESTATE Raw Value-77',
        ('zShare-Trashed Date-78', 'datetime'),
        ('zShare-LastParticipant Asset Trash Notification Date-79', 'datetime'),
        ('zShare-Last Participant Asset Trash Notification View Date-80', 'datetime'),
        'zShare-Z_ENT Raw Value-81')
# data_list = get_sqlite_db_records(source_path, null_absent_columns(source_path, query))

        return data_headers, data_list, source_path

    elif (version.parse(iosversion) >= version.parse("18")) & (version.parse(iosversion) < version.parse("26")):
        source_path = get_file_path(files_found,"Photos.sqlite")
        if source_path is None or not os.path.exists(source_path):
            logfunc(f"Photos.sqlite not found for iOS version {iosversion}")
            return (), [], source_path
        data_list = []

        query = '''
        SELECT
        DateTime(zShare.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Creation Date',
        DateTime(zShare.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Start Date',
        DateTime(zShare.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'zShare-End Date',
        DateTime(zShare.ZEXPIRYDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Expiry Date',
        DateTime(zAsset.ZDATECREATED + 978307200, 'UNIXEPOCH') AS 'zAsset-Date Created',
        zAsset.Z_PK AS 'zAsset-zPK',
        zAsset.ZDIRECTORY AS 'zAsset-Directory-Path',
        zAsset.ZFILENAME AS 'zAsset-Filename',
        zAddAssetAttr.ZORIGINALFILENAME AS 'zAddAssetAttr- Original Filename',
        zCldMast.ZORIGINALFILENAME AS 'zCldMast- Original Filename',
        zAddAssetAttr.ZSYNDICATIONIDENTIFIER AS 'zAddAssetAttr- Syndication Identifier-SWY-Files',
        zAsset.ZSYNDICATIONSTATE AS 'zAsset-ZSYNDICATIONSTATE Raw Value',
        zAsset.ZBUNDLESCOPE AS 'zAsset-ZBUNDLESCOPE Raw Value',
        zAddAssetAttr.ZIMPORTEDBY AS 'zAddAssetAttr-ZIMPORTEDBY Raw Value',
        zExtAttr.ZCAMERAMAKE AS 'zExtAttr-Camera Make',
        zExtAttr.ZCAMERAMODEL AS 'zExtAttr-Camera Model',
        zAddAssetAttr.ZIMPORTEDBYBUNDLEIDENTIFIER AS 'zAddAssetAttr- Imported by Bundle Identifier',
        zAddAssetAttr.ZIMPORTEDBYDISPLAYNAME AS 'zAddAssetAttr- Imported By Display Name',
        zAsset.ZVISIBILITYSTATE AS 'zAsset-ZVISIBILITYSTATE Raw Value',
        zAsset.ZSAVEDASSETTYPE AS 'zAsset-ZSAVEDASSETTYPE Raw Value',
        zAddAssetAttr.ZSHARETYPE AS 'zAddAssetAttr-ZSHARETYPE Raw Value',
        zAsset.ZACTIVELIBRARYSCOPEPARTICIPATIONSTATE AS 'zAsset-ZACTIVELIBRARYSCOPEPARTICIPATIONSTATE Raw Value',
        DateTime(zAsset.ZSORTTOKEN + 978307200, 'UNIXEPOCH') AS 'zAsset- SortToken -CameraRoll',
        DateTime(zAsset.ZADDEDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Added Date',        
        DateTime(zCldMast.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'zCldMast-Creation Date',
        zAddAssetAttr.ZTIMEZONENAME AS 'zAddAssetAttr-Time Zone Name',
        zAddAssetAttr.ZEXIFTIMESTAMPSTRING AS 'zAddAssetAttr-EXIF-String',
        DateTime(zAsset.ZMODIFICATIONDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Modification Date',
        DateTime(zAsset.ZLASTSHAREDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Last Shared Date',
        zAsset.ZHIDDEN AS 'zAsset-ZHIDDEN Raw Value',
        zAsset.ZAVALANCHEPICKTYPE AS 'zAsset-ZAVALANCHEPICKTYPE Raw Value',
        zAddAssetAttr.ZCLOUDAVALANCHEPICKTYPE AS 'zAddAssetAttr-ZCLOUDAVALANCHEPICKTYPE Raw Value',
        zAsset.ZTRASHEDSTATE AS 'zAsset-ZTRASHEDSTATE Raw Value',
        DateTime(zAsset.ZTRASHEDDATE + 978307200, 'UNIXEPOCH') AS 'zAsset-Trashed Date',
        zAsset.ZTRASHEDBYPARTICIPANT AS 'zAsset-Trashed by Participant= zShareParticipant_zPK',
        zAddAssetAttr.Z_PK AS 'zAddAssetAttr-zPK',
        zAsset.ZUUID AS 'zAsset-UUID = store.cloudphotodb',
        zAddAssetAttr.ZORIGINALSTABLEHASH AS 'zAddAssetAttr-Original Stable Hash',
        zAddAssetAttr.ZADJUSTEDSTABLEHASH AS 'zAddAssetAttr.Adjusted Stable Hash',  
        zShare.ZUUID AS 'zShare-UUID',
        zShare.ZORIGINATINGSCOPEIDENTIFIER AS 'zShare-Originating Scope ID',
        zSharePartic.Z61_SHARE AS 'zSharePartic-Z61_SHARE Raw Value',
        zShare.ZSTATUS AS 'zShare-ZSTATUS Raw Value',
        zShare.ZSCOPETYPE AS 'zShare-ZSCOPETYPE Raw Value',
        zShare.ZASSETCOUNT AS 'zShare-Asset Count-CMM',
        zShare.ZFORCESYNCATTEMPTED AS 'zShare-Force Sync Attempted-CMM',  
        zShare.ZPHOTOSCOUNT AS 'zShare-Photos Count-CMM',
        zShare.ZUPLOADEDPHOTOSCOUNT AS 'zShare-Uploaded Photos Count-CMM',
        zShare.ZVIDEOSCOUNT AS 'zShare-Videos Count-CMM',
        zShare.ZUPLOADEDVIDEOSCOUNT AS 'zShare-Uploaded Videos Count-CMM',  
        zShare.ZSCOPEIDENTIFIER AS 'zShare-Scope ID',
        zShare.ZTITLE AS 'zShare-Title-SPL',
        zShare.ZSHAREURL AS 'zShare-Share URL',
        zShare.ZLOCALPUBLISHSTATE AS 'zShare-ZLOCALPUBLISHSTATE Raw Value',
        zShare.ZPUBLICPERMISSION AS 'zShare-ZPUBLICPERMISSION Raw Value',
        zShare.ZCLOUDLOCALSTATE AS 'zShare-ZCLOUDLOCALSTATE Raw Value',
        zShare.ZSCOPESYNCINGSTATE AS 'zShare-ZSCOPESYNCINGSTATE Raw Value',
        zShare.ZAUTOSHAREPOLICY AS 'zShare-ZAUTOSHAREPOLICY Raw Value',
        zSharePartic.ZACCEPTANCESTATUS AS 'zSharePartic-ZACCEPTANCESTATUS Raw Value',
        zSharePartic.ZUSERIDENTIFIER AS 'zSharePartic-User ID',
        zSharePartic.Z_PK AS 'zSharePartic-zPK',
        zSharePartic.ZEMAILADDRESS AS 'zSharePartic-Email Address',
        zSharePartic.ZPHONENUMBER AS 'zSharePartic-Phone Number',
        zSharePartic.ZPARTICIPANTID AS 'zSharePartic-Participant ID',
        zSharePartic.ZUUID AS 'zSharePartic-UUID',  
        zSharePartic.ZISCURRENTUSER AS 'zSharePartic-ZISCURRENTUSER Raw Value',
        zSharePartic.ZROLE AS 'zSharePartic-ZROLE Raw Value',
        zSharePartic.ZPERMISSION AS 'zSharePartic-ZPERMISSION Raw Value',
        zShare.ZPARTICIPANTCLOUDUPDATESTATE AS 'zShare-ZPARTICIPANTCLOUDUPDATESTATE Raw Value',
        zSharePartic.ZEXITSTATE AS 'zSharePartic-ZEXITSTATE Raw Value',
        zShare.ZPREVIEWSTATE AS 'zShare-ZPREVIEWSTATE Raw Value',
        zShare.ZSHOULDNOTIFYONUPLOADCOMPLETION AS 'zShare-ZSHOULDNOTIFYONUPLOADCOMPLETION Raw Value',
        zShare.ZSHOULDIGNOREBUDGETS AS 'zShare-ZSHOULDIGNOREBUDGETS Raw Value',
        zShare.ZEXITSOURCE AS 'zShare-ZEXITSOURCE Raw Value',
        zShare.ZEXITSTATE AS 'zShare-ZEXITSTATE Raw Value',
        zShare.ZEXITTYPE AS 'zShare-ZEXITTYPE Raw Value',
        zShare.ZTRASHEDSTATE AS 'zShare-ZTRASHEDSTATE Raw Value',
        zShare.ZCLOUDDELETESTATE AS 'zShare-ZCLOUDDELETESTATE Raw Value',
        DateTime(zShare.ZTRASHEDDATE + 978307200, 'UNIXEPOCH') AS 'zShare-Trashed Date',
        DateTime(zShare.ZLASTPARTICIPANTASSETTRASHNOTIFICATIONDATE + 978307200, 'UNIXEPOCH') AS
         'zShare-LastParticipant Asset Trash Notification Date',
        DateTime(zShare.ZLASTPARTICIPANTASSETTRASHNOTIFICATIONVIEWEDDATE + 978307200, 'UNIXEPOCH') AS
         'zShare-Last Participant Asset Trash Notification View Date',
        zShare.Z_ENT AS 'zShare-Z_ENT Raw Value'
        FROM ZASSET zAsset
            LEFT JOIN ZADDITIONALASSETATTRIBUTES zAddAssetAttr ON zAddAssetAttr.Z_PK = zAsset.ZADDITIONALATTRIBUTES
            LEFT JOIN ZEXTENDEDATTRIBUTES zExtAttr ON zExtAttr.Z_PK = zAsset.ZEXTENDEDATTRIBUTES
            LEFT JOIN ZCLOUDMASTER zCldMast ON zAsset.ZMASTER = zCldMast.Z_PK
            LEFT JOIN ZSHARE zShare ON zShare.Z_PK = zAsset.ZMOMENTSHARE
            LEFT JOIN ZSHAREPARTICIPANT zSharePartic ON zSharePartic.ZSHARE = zShare.Z_PK
        WHERE zAsset.ZSAVEDASSETTYPE = 8
        ORDER BY zShare.ZCREATIONDATE
        '''

        db_records = get_sqlite_db_records(source_path, null_absent_columns(source_path, query))
        for row in db_records:
            data_list.append((row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9],
            row[10], row[11], row[12], row[13], row[14], row[15], row[16], row[17], row[18],
            row[19], row[20], row[21], row[22], row[23], row[24], row[25], row[26], row[27],
            row[28], row[29], row[30], row[31], row[32], row[33], row[34], row[35], row[36],
            row[37], row[38], row[39], row[40], row[41], row[42], row[43], row[44], row[45],
            row[46], row[47], row[48], row[49], row[50], row[51], row[52], row[53], row[54],
            row[55], row[56], row[57], row[58], row[59], row[60], row[61], row[62], row[63],
            row[64], row[65], row[66], row[67], row[68], row[69], row[70], row[71], row[72],
            row[73], row[74], row[75], row[76], row[77], row[78], row[79], row[80], row[81]))

        data_headers = (('zShare-Creation Date-0', 'datetime'),
        ('zShare-Start Date-1', 'datetime'),
        ('zShare-End Date-2', 'datetime'),
        ('zShare-Expiry Date-3', 'datetime'),
        ('zAsset-Date Created-4', 'datetime'),
        'zAsset-zPK-5',
        'zAsset-Directory-Path-6',
        'zAsset-Filename-7',
        'zAddAssetAttr- Original Filename-8',
        'zCldMast- Original Filename-9',
        'zAddAssetAttr- Syndication Identifier-SWY-Files-10',
        'zAsset-ZSYNDICATIONSTATE Raw Value-11',
        'zAsset-ZBUNDLESCOPE Raw Value-12',
        'zAddAssetAttr-ZIMPORTEDBY Raw Value-13',
        'zExtAttr-Camera Make-14',
        'zExtAttr-Camera Model-15',
        'zAddAssetAttr- Imported by Bundle Identifier-16',
        'zAddAssetAttr- Imported By Display Name-17',
        'zAsset-ZVISIBILITYSTATE Raw Value-18',
        'zAsset-ZSAVEDASSETTYPE Raw Value-19',
        'zAddAssetAttr-ZSHARETYPE Raw Value-20',
        'zAsset-ZACTIVELIBRARYSCOPEPARTICIPATIONSTATE Raw Value-21',
        ('zAsset- SortToken -CameraRoll-22', 'datetime'),
        ('zAsset-Added Date-23', 'datetime'),
        ('zCldMast-Creation Date-24', 'datetime'),
        'zAddAssetAttr-Time Zone Name-25',
        'zAddAssetAttr-EXIF-String-26',
        ('zAsset-Modification Date-27', 'datetime'),
        ('zAsset-Last Shared Date-28', 'datetime'),
        'zAsset-ZHIDDEN Raw Value-29',
        'zAsset-ZAVALANCHEPICKTYPE Raw Value-30',
        'zAddAssetAttr-ZCLOUDAVALANCHEPICKTYPE Raw Value-31',
        'zAsset-ZTRASHEDSTATE Raw Value-32',
        ('zAsset-Trashed Date-33', 'datetime'),
        'zAsset-Trashed by Participant= zShareParticipant_zPK-34',
        'zAddAssetAttr-zPK-35',
        'zAsset-UUID = store.cloudphotodb-36',
        'zAddAssetAttr-Original Stable Hash-37',
        'zAddAssetAttr.Adjusted Stable Hash-38',
        'zShare-UUID-39',
        'zShare-Originating Scope ID-40',
        'zSharePartic-Z61_SHARE Raw Value-41',
        'zShare-ZSTATUS Raw Value-42',
        'zShare-ZSCOPETYPE Raw Value-43',
        'zShare-Asset Count-CMM-44',
        'zShare-Force Sync Attempted-CMM-45',
        'zShare-Photos Count-CMM-46',
        'zShare-Uploaded Photos Count-CMM-47',
        'zShare-Videos Count-CMM-48',
        'zShare-Uploaded Videos Count-CMM-49',
        'zShare-Scope ID-50',
        'zShare-Title-SPL-51',
        'zShare-Share URL-52',
        'zShare-ZLOCALPUBLISHSTATE Raw Value-53',
        'zShare-ZPUBLICPERMISSION Raw Value-54',
        'zShare-ZCLOUDLOCALSTATE Raw Value-55',
        'zShare-ZSCOPESYNCINGSTATE Raw Value-56',
        'zShare-ZAUTOSHAREPOLICY Raw Value-57',
        'zSharePartic-ZACCEPTANCESTATUS Raw Value-58',
        'zSharePartic-User ID-59',
        'zSharePartic-zPK-60',
        'zSharePartic-Email Address-61',
        'zSharePartic-Phone Number-62',
        'zSharePartic-Participant ID-63',
        'zSharePartic-UUID-64',
        'zSharePartic-ZISCURRENTUSER Raw Value-65',
        'zSharePartic-ZROLE Raw Value-66',
        'zSharePartic-ZPERMISSION Raw Value-67',
        'zShare-ZPARTICIPANTCLOUDUPDATESTATE Raw Value-68',
        'zSharePartic-ZEXITSTATE Raw Value-69',
        'zShare-ZPREVIEWSTATE Raw Value-70',
        'zShare-ZSHOULDNOTIFYONUPLOADCOMPLETION Raw Value-71',
        'zShare-ZSHOULDIGNOREBUDGETS Raw Value-72',
        'zShare-ZEXITSOURCE Raw Value-73',
        'zShare-ZEXITSTATE Raw Value-74',
        'zShare-ZEXITTYPE Raw Value-75',
        'zShare-ZTRASHEDSTATE Raw Value-76',
        'zShare-ZCLOUDDELETESTATE Raw Value-77',
        ('zShare-Trashed Date-78', 'datetime'),
        ('zShare-LastParticipant Asset Trash Notification Date-79', 'datetime'),
        ('zShare-Last Participant Asset Trash Notification View Date-80', 'datetime'),
        'zShare-Z_ENT Raw Value-81')
# data_list = get_sqlite_db_records(source_path, null_absent_columns(source_path, query))

        return data_headers, data_list, source_path
