# ---------------------------------------------------------------------------
# Vendored into iLEAPP from mmkv-parser (github.com/abrignoni/mmkv-parser)
# by Alexis Brignoni, MIT, unchanged except for this banner:
#   * upstream commit 035b92dec07bb207af6ca5a05da796aa9d893f30 (2026-09-04).
#   * upstream file mmkv_parser/__init__.py.
# Do not edit this file in place. A change here is reverted by the next
# re-vendor, and admin/scripts/check_vendored.py fetches the upstream file at
# the commit above and fails CI when anything below this banner differs from
# it. Fix it upstream, re-vendor, then update the commit line above.
# ---------------------------------------------------------------------------
"""MMKV key-value store reader.

MMKV is Tencent's mmap-backed key-value store, used by a number of Android and
iOS apps in place of SharedPreferences or NSUserDefaults
(github.com/Tencent/MMKV, BSD-3-Clause). Its on-disk layout is small enough to
read directly:

    [0:4]   actual size of the data region, uint32 little-endian
    [4:4+actual_size]
            the data region. It opens with one varint, the total size of the
            items that follow (Tencent's MMKV_IO.cpp reserves a fixed 4-byte
            slot for it on the append path, ItemSizeHolderSize, and writes a
            plain varint on the full-rewrite path in MiniPBCoder.cpp, so on
            disk it is 1 to 4 bytes long). After it, entries laid end to end,
            each one
                varint  key length
                bytes   key, UTF-8
                varint  value container length
                bytes   value container
    the remainder of the file is zero padding out to the mmap page size

The value container is untyped on disk. MMKV records the type in the calling
code, not in the file, so this module returns the raw container and leaves the
reading to the caller. `decode_value` applies the one distinction that can be
made from the bytes alone: a container that is exactly a varint length followed
by that many bytes is how MMKV writes a string, and anything else is read as a
varint scalar, which is how it writes the integer and boolean types.

Two properties matter when reading one of these files as evidence.

**The store is append-only between rewrites.** Setting a key appends a new
entry rather than editing the existing one, so a key that has been changed
appears more than once and the earlier entries are superseded values still
present in the file. `read_entries` returns every entry in file order so those
remain visible; `read_dict` collapses to the last occurrence, which is the value
the app reads.

**A zero-length container marks a removal**, not an empty string. `read_dict`
drops those keys, matching what the app sees. They stay visible in
`read_entries`.

**Which size bounds the read.** The four-byte header is not the only record of the
data region's length: from meta version 3 the sibling ``<name>.crc`` file carries
its own copy at bytes 28 to 32, and that is the one MMKV itself reads
(``MMKV::readActualSize``). Releases up to 2.3.0 wrote both on every write, so they
agree; 2.4.0 stopped maintaining the header for stores at that version. This module
therefore prefers the meta file's size when the meta version is 3 or higher and the
value fits inside the file, and falls back to the header otherwise. Measured on 1,771
stores from 55 iOS and Android extractions, the two agreed on every one, so the
preference changes nothing on stores written by any release to date.

**Decryption is opt-in and needs the key.** MMKV supports an AES-CFB mode; the
initialisation vector for it is kept in the meta file at bytes 12 to 28, and the key
is not in either file. With no ``key`` argument an encrypted store raises MMKVError
rather than returning the garbage keys an encrypted region decodes to. Given a
``key``, the region is decrypted and read, and a key that does not produce a
structurally complete store raises rather than returning a partial garbage read.
Nothing here looks for a key, and a key is ignored for a store that is not
encrypted. Decryption needs `pycryptodome` or `cryptography` installed; the reader
itself has no dependencies and everything else works without them.
"""

import struct


class MMKVError(Exception):
    """Raised when a file cannot be read as an MMKV store."""


_HEADER_LENGTH = 4
# Ten sevens covers a 64-bit value, which is the widest scalar MMKV writes.
# A varint longer than that means the walk has lost alignment.
_MAX_VARINT_BYTES = 10
# MMKVMetaInfo: crc u32, version u32, sequence u32, aesVector[16], actualSize u32.
_META_LENGTH = 32
_META_VECTOR = slice(12, 28)
_META_ACTUAL_SIZE_OFFSET = 28
# MMKVVersionActualSize: from this meta version the meta file carries the region size.
_META_VERSION_ACTUAL_SIZE = 3
# AESCrypt copies min(len(key), 16 or 32) bytes into a zero-filled buffer of that
# length, so a short key is zero-padded and a long one truncated.
_AES128_KEY_LENGTH = 16
_AES256_KEY_LENGTH = 32


def _read_varint(data, offset):
    """Return (value, new_offset) for the varint at offset."""
    result = 0
    shift = 0
    for _ in range(_MAX_VARINT_BYTES):
        if offset >= len(data):
            raise MMKVError('varint runs past end of data')
        byte = data[offset]
        offset += 1
        result |= (byte & 0x7F) << shift
        if not byte & 0x80:
            return result, offset
        shift += 7
    raise MMKVError('varint longer than 5 bytes')


def read_entries(path, key=None, aes256=False):
    """Return every (key, raw_value_container) entry in file order.

    Every entry is returned, including repeats of the same key. Later entries
    for a key supersede earlier ones; see read_dict for the collapsed view.

    ``key`` decrypts an AES-encrypted store. Pass the key the application uses,
    as bytes or as a string; nothing here looks for it. It is ignored for a store
    that is not encrypted. ``aes256`` selects AES-256 for a store the application
    created that way; the MMKV default is AES-128 and so is this one.

    Raises MMKVError for a file that is not a readable MMKV store, for an
    encrypted store with no key, for a key that does not decrypt the store, and
    for an encrypted store when no crypto backend is installed.
    """
    with open(path, 'rb') as handle:
        data = handle.read()
    if len(data) < _HEADER_LENGTH:
        raise MMKVError('file shorter than an MMKV header')
    meta = _read_meta(path)
    region_size = _region_size(data, meta)
    if region_size == 0:
        return []
    if _HEADER_LENGTH + region_size > len(data):
        raise MMKVError('recorded data size runs past the end of the file')
    region = data[_HEADER_LENGTH:_HEADER_LENGTH + region_size]

    vector = meta['vector'] if meta else b''
    if vector:
        if key is None:
            raise MMKVError('store is AES-encrypted (non-zero vector in the .crc meta file)')
        region = _decrypt(region, _key_material(key, aes256), vector)
        entries, unread = _walk(region)
        # Every one of the 846 readable stores measured across 55 extractions was
        # walked to its last byte, so a decryption that leaves a tail unread, or
        # yields nothing at all, did not produce an MMKV store and the key is wrong.
        if not entries or unread:
            raise MMKVError('the supplied key did not decrypt this store')
        return entries
    return _walk(region)[0]


def _walk(region):
    """Return (entries, bytes left unread) for a decrypted or plaintext data region.

    The region opens with the items-size varint; the first key follows it. A
    walk that loses alignment stops and keeps what it read, which is why the
    count of unread bytes is returned rather than raised: for a plaintext store
    a short read is the honest answer, and for a decrypted one it is the tell
    that the key was wrong.
    """
    entries = []
    try:
        _items_size, offset = _read_varint(region, 0)
    except MMKVError:
        return entries, len(region)
    end = len(region)
    while offset < end:
        try:
            key_length, offset = _read_varint(region, offset)
            if key_length == 0 or offset + key_length > end:
                break
            key = region[offset:offset + key_length].decode('utf-8')
            offset += key_length
            value_length, offset = _read_varint(region, offset)
            if offset + value_length > end:
                break
            entries.append((key, region[offset:offset + value_length]))
            offset += value_length
        except (MMKVError, UnicodeDecodeError):
            break
    return entries, end - offset


def _read_meta(path):
    """Return the sibling .crc meta file's fields, or None when it is absent or short.

    MMKVMetaInfo lays out: crc u32, version u32, sequence u32, aesVector[16],
    actualSize u32. A vector of all zeros means the store is not encrypted.
    """
    try:
        with open(path + '.crc', 'rb') as handle:
            head = handle.read(_META_LENGTH)
    except OSError:
        return None
    if len(head) < _META_VECTOR.stop:
        return None
    vector = head[_META_VECTOR]
    # actualSize sits past the vector, so a meta file too short to hold it is read
    # for the vector alone and the header keeps its job of bounding the region.
    has_size = len(head) >= _META_LENGTH
    return {'version': struct.unpack_from('<I', head, 4)[0],
            'sequence': struct.unpack_from('<I', head, 8)[0],
            'vector': vector if any(vector) else b'',
            'actual_size': struct.unpack_from('<I', head, _META_ACTUAL_SIZE_OFFSET)[0]
                           if has_size else None}


def _region_size(data, meta):
    """Return the length of the data region, from the meta file where that is the record.

    MMKV::readActualSize takes the size from the meta file once its version is 3,
    and only from the header below that. A meta size that does not fit inside the
    file is not usable, so the header is read instead.
    """
    header_size = struct.unpack_from('<I', data, 0)[0]
    if meta and meta['version'] >= _META_VERSION_ACTUAL_SIZE and meta['actual_size'] is not None:
        if meta['actual_size'] <= len(data) - _HEADER_LENGTH:
            return meta['actual_size']
    return header_size


def _key_material(key, aes256=False):
    """Return the key bytes as AESCrypt takes them: truncated, then zero-padded.

    AESCrypt copies min(len(key), 16 or 32) bytes into a zero-filled buffer of
    that length, so a short key is padded with zeros and a long one is cut.
    """
    if isinstance(key, str):
        key = key.encode('utf-8')
    if not isinstance(key, (bytes, bytearray)):
        raise MMKVError('key must be bytes or a string')
    if not key:
        raise MMKVError('key is empty')
    length = _AES256_KEY_LENGTH if aes256 else _AES128_KEY_LENGTH
    return bytes(key[:length]).ljust(length, b'\x00')


def _decrypt(region, key, vector):
    """Decrypt a data region with AES-CFB128, the mode MMKV uses.

    Tries pycryptodome first, then cryptography. Neither is a dependency of this
    module: everything except decryption works with no packages installed.

    pycryptodome's MODE_CFB defaults to 8-bit segments, which silently returns
    something other than what MMKV wrote, so the segment size is passed
    explicitly. Both backends are checked against the published CFB128-AES128
    vector in the tests.
    """
    try:
        from Crypto.Cipher import AES  # pylint: disable=import-outside-toplevel
        return AES.new(key, AES.MODE_CFB, vector, segment_size=128).decrypt(region)
    except ImportError:
        pass
    try:
        # CFB moved to the decrepit module in cryptography 43 and is being removed
        # from the original location, so try its new home first.
        try:
            from cryptography.hazmat.decrepit.ciphers.modes import (  # pylint: disable=import-outside-toplevel
                CFB)
        except ImportError:
            from cryptography.hazmat.primitives.ciphers.modes import (  # pylint: disable=import-outside-toplevel
                CFB)
        from cryptography.hazmat.primitives.ciphers import (  # pylint: disable=import-outside-toplevel
            Cipher, algorithms)
        decryptor = Cipher(algorithms.AES(key), CFB(vector)).decryptor()
        return decryptor.update(region) + decryptor.finalize()
    except ImportError as exc:
        raise MMKVError('decrypting needs pycryptodome or cryptography installed; '
                        'neither was importable') from exc


def decode_value(container):
    """Decode a value container to a str or an int.

    A container that is exactly a varint length followed by that many bytes is
    how MMKV writes a string; anything else is read as a varint scalar, which
    covers its integer and boolean types. Returns None for a removal marker,
    and the raw bytes when neither reading applies.
    """
    if not container:
        return None
    try:
        length, offset = _read_varint(container, 0)
    except MMKVError:
        return container
    if offset + length == len(container):
        try:
            return container[offset:offset + length].decode('utf-8')
        except UnicodeDecodeError:
            return container[offset:offset + length]
    try:
        value, offset = _read_varint(container, 0)
    except MMKVError:
        return container
    if offset == len(container):
        return value
    return container


def read_dict(path, key=None, aes256=False):
    """Return {key: decoded value} using the last occurrence of each key.

    Removed keys are omitted. Use read_entries when the superseded values
    matter. ``key`` and ``aes256`` are passed through to read_entries.
    """
    result = {}
    for entry_key, container in read_entries(path, key=key, aes256=aes256):
        value = decode_value(container)
        if value is None:
            result.pop(entry_key, None)
        else:
            result[entry_key] = value
    return result
