# ---------------------------------------------------------------------------
# Vendored into iLEAPP from mmkv-parser (github.com/abrignoni/mmkv-parser)
# by Alexis Brignoni, MIT, unchanged except for this banner:
#   * upstream commit 410ddb22df025859ab5ef522a3ca6e94b22d663e (2026-09-07).
#   * upstream file mmkv_parser/__init__.py.
# Do not edit this file in place. A change here is reverted by the next
# re-vendor, and admin/scripts/check_vendored.py fetches the upstream file at
# the commit above and fails CI when anything below this banner differs from
# it. Fix it upstream, re-vendor, then update the commit line above.
# ---------------------------------------------------------------------------
"""MMKV key-value store reader.

MMKV is Tencent's mmap-backed key-value store, used by a number of Android and
iOS apps in place of SharedPreferences or NSUserDefaults
(github.com/Tencent/MMKV, BSD-3-Clause). Its on-disk layout is small enough to
read directly:

    [0:4]   actual size of the data region, uint32 little-endian
    [4:4+actual_size]
            the data region. It opens with one varint, the total size of the
            items that follow (Tencent's MMKV_IO.cpp reserves a fixed 4-byte
            slot for it on the append path, ItemSizeHolderSize, and writes a
            plain varint on the full-rewrite path in MiniPBCoder.cpp, so on
            disk it is 1 to 4 bytes long). After it, entries laid end to end,
            each one
                varint  key length
                bytes   key, UTF-8
                varint  value container length
                bytes   value container
    the remainder of the file is zero padding out to the mmap page size

The value container is untyped on disk. MMKV records the type in the calling
code, not in the file, so this module returns the raw container and leaves the
reading to the caller. `decode_value` applies the one distinction that can be
made from the bytes alone: a container that is exactly a varint length followed
by that many bytes is how MMKV writes a string, and anything else is read as a
varint scalar, which is how it writes the integer and boolean types.

Two properties matter when reading one of these files as evidence.

**The store is append-only between rewrites.** Setting a key appends a new
entry rather than editing the existing one, so a key that has been changed
appears more than once and the earlier entries are superseded values still
present in the file. `read_entries` returns every entry in file order so those
remain visible; `read_dict` collapses to the last occurrence, which is the value
the app reads.

**A zero-length container marks a removal**, not an empty string. `read_dict`
drops those keys, matching what the app sees. They stay visible in
`read_entries`.

**Which size bounds the read.** The four-byte header is not the only record of the
data region's length: from meta version 3 the sibling ``<name>.crc`` file carries
its own copy at bytes 28 to 32, and that is the one MMKV itself reads
(``MMKV::readActualSize``). Releases up to 2.3.0 wrote both on every write, so they
agree; 2.4.0 stopped maintaining the header for stores at that version. This module
therefore prefers the meta file's size when the meta version is 3 or higher and the
value fits inside the file, and falls back to the header otherwise. Measured on 1,771
stores from 55 iOS and Android extractions, the two agreed on every one, so the
preference changes nothing on stores written by any release to date.

**A recorded size of zero does not mean the records are gone.** When MMKV clears a
store, and when it loads one whose CRC does not check out, it writes a size of zero
into the meta file and leaves the data region untouched: ``MMKV::clearAll`` truncates
to the expected capacity and calls ``writeActualSize(0, 0, ...)``, and the load path's
"file not valid or empty, discard everything" branch does the same. Neither zeroes the
records. Such a store reads as empty, which is what the app sees and what this module
returns by default. ``recover=True`` walks the region anyway, and returns entries only
when the walk consumes whole entries and then meets nothing but the zero padding, so a
region that does not account for itself is left alone rather than guessed at. This is a
walk of the ordinary layout, not a search: no offset is scanned and no record is
inferred. Measured on 16 such stores from one iOS extraction, every one walked to clean
padding, recovering 1 to 46 entries each.
**What sits past the recorded size is the store's own former content.** MMKV
compacts by moving the surviving entries to the front of the region with a memmove
and lowering the recorded size (``MMKV_IO.cpp``, ``memmoveDictionary`` and
``doFullWriteBack``); nothing zeroes what the move leaves behind, and growth is the
only operation that zero-fills, so the bytes between the recorded size and the end
of the file are earlier generations of this store and never another file's.
``carve_slack`` reads records out of that space. It is inference rather than
parsing: see its docstring for what it can and cannot establish.

**Decryption is opt-in and needs the key.** MMKV supports an AES-CFB mode; the
initialisation vector for it is kept in the meta file at bytes 12 to 28, and the key
is not in either file. With no ``key`` argument an encrypted store raises MMKVError
rather than returning the garbage keys an encrypted region decodes to. Given a
``key``, the region is decrypted and read, and a key that does not produce a
structurally complete store raises rather than returning a partial garbage read.
Nothing here looks for a key, and a key is ignored for a store that is not
encrypted. Decryption needs `pycryptodome` or `cryptography` installed; the reader
itself has no dependencies and everything else works without them.
"""

import collections
import re
import struct


class MMKVError(Exception):
    """Raised when a file cannot be read as an MMKV store."""


_HEADER_LENGTH = 4
# Ten sevens covers a 64-bit value, which is the widest scalar MMKV writes.
# A varint longer than that means the walk has lost alignment.
_MAX_VARINT_BYTES = 10
# MMKVMetaInfo: crc u32, version u32, sequence u32, aesVector[16], actualSize u32.
_META_LENGTH = 32
_META_VECTOR = slice(12, 28)
_META_ACTUAL_SIZE_OFFSET = 28
# MMKVVersionActualSize: from this meta version the meta file carries the region size.
_META_VERSION_ACTUAL_SIZE = 3
# AESCrypt copies min(len(key), 16 or 32) bytes into a zero-filled buffer of that
# length, so a short key is zero-padded and a long one truncated.
_AES128_KEY_LENGTH = 16
_AES256_KEY_LENGTH = 32


def _read_varint(data, offset):
    """Return (value, new_offset) for the varint at offset."""
    result = 0
    shift = 0
    for _ in range(_MAX_VARINT_BYTES):
        if offset >= len(data):
            raise MMKVError('varint runs past end of data')
        byte = data[offset]
        offset += 1
        result |= (byte & 0x7F) << shift
        if not byte & 0x80:
            return result, offset
        shift += 7
    raise MMKVError('varint longer than 5 bytes')


def read_entries(path, key=None, aes256=False, recover=False):
    """Return every (key, raw_value_container) entry in file order.

    Every entry is returned, including repeats of the same key. Later entries
    for a key supersede earlier ones; see read_dict for the collapsed view.

    ``key`` decrypts an AES-encrypted store. Pass the key the application uses,
    as bytes or as a string; nothing here looks for it. It is ignored for a store
    that is not encrypted. ``aes256`` selects AES-256 for a store the application
    created that way; the MMKV default is AES-128 and so is this one.

    ``recover`` applies only to a store whose recorded size is zero, the state MMKV
    leaves behind when it clears a store or fails a store's CRC. It walks the
    surviving region and returns what it finds, and returns nothing when the region
    does not walk cleanly to its zero padding. It changes nothing for any other store.

    Raises MMKVError for a file that is not a readable MMKV store, for an
    encrypted store with no key, for a key that does not decrypt the store, for an
    encrypted store when no crypto backend is installed, and for a recover of a
    reset store that is encrypted.
    """
    with open(path, 'rb') as handle:
        data = handle.read()
    if len(data) < _HEADER_LENGTH:
        raise MMKVError('file shorter than an MMKV header')
    meta = _read_meta(path)
    region_size = _region_size(data, meta)
    if region_size == 0:
        if not recover:
            return []
        if meta and meta['vector']:
            raise MMKVError(
                'cannot recover a reset store that is encrypted: the meta file holds the '
                'vector written when the store was reset, not the one the surviving region '
                'was written under')
        return _recover_reset_region(data)
    if _HEADER_LENGTH + region_size > len(data):
        raise MMKVError('recorded data size runs past the end of the file')
    region = data[_HEADER_LENGTH:_HEADER_LENGTH + region_size]

    vector = meta['vector'] if meta else b''
    if vector:
        if key is None:
            raise MMKVError('store is AES-encrypted (non-zero vector in the .crc meta file)')
        region = _decrypt(region, _key_material(key, aes256), vector)
        entries, unread = _walk(region)
        # Every one of the 846 readable stores measured across 55 extractions was
        # walked to its last byte, so a decryption that leaves a tail unread, or
        # yields nothing at all, did not produce an MMKV store and the key is wrong.
        if not entries or unread:
            raise MMKVError('the supplied key did not decrypt this store')
        return entries
    return _walk(region)[0]


def _walk(region):
    """Return (entries, bytes left unread) for a decrypted or plaintext data region.

    The region opens with the items-size varint; the first key follows it. A
    walk that loses alignment stops and keeps what it read, which is why the
    count of unread bytes is returned rather than raised: for a plaintext store
    a short read is the honest answer, and for a decrypted one it is the tell
    that the key was wrong.
    """
    entries = []
    try:
        _items_size, offset = _read_varint(region, 0)
    except MMKVError:
        return entries, len(region)
    end = len(region)
    while offset < end:
        try:
            key_length, offset = _read_varint(region, offset)
            if key_length == 0 or offset + key_length > end:
                break
            key = region[offset:offset + key_length].decode('utf-8')
            offset += key_length
            value_length, offset = _read_varint(region, offset)
            if offset + value_length > end:
                break
            entries.append((key, region[offset:offset + value_length]))
            offset += value_length
        except (MMKVError, UnicodeDecodeError):
            break
    return entries, end - offset


def _recover_reset_region(data):
    """Return the entries of a store whose recorded size is zero but whose region survives.

    Only returned when the walk accounts for the whole region: whole entries followed by
    nothing but the zero padding MMKV pads the file out to. A region carrying anything
    else is the leftover of a rewrite rather than an intact abandoned store, and reading
    it needs the record-by-record tests of a carve, not this walk, so nothing is returned
    for it here.
    """
    body = data[_HEADER_LENGTH:]
    if not any(body):
        return []
    entries, unread = _walk(body)
    if not entries or any(body[len(body) - unread:]):
        return []
    return entries


def _read_meta(path):
    """Return the sibling .crc meta file's fields, or None when it is absent or short.

    MMKVMetaInfo lays out: crc u32, version u32, sequence u32, aesVector[16],
    actualSize u32. A vector of all zeros means the store is not encrypted.
    """
    try:
        with open(path + '.crc', 'rb') as handle:
            head = handle.read(_META_LENGTH)
    except OSError:
        return None
    if len(head) < _META_VECTOR.stop:
        return None
    vector = head[_META_VECTOR]
    # actualSize sits past the vector, so a meta file too short to hold it is read
    # for the vector alone and the header keeps its job of bounding the region.
    has_size = len(head) >= _META_LENGTH
    return {'version': struct.unpack_from('<I', head, 4)[0],
            'sequence': struct.unpack_from('<I', head, 8)[0],
            'vector': vector if any(vector) else b'',
            'actual_size': struct.unpack_from('<I', head, _META_ACTUAL_SIZE_OFFSET)[0]
                           if has_size else None}


def _region_size(data, meta):
    """Return the length of the data region, from the meta file where that is the record.

    MMKV::readActualSize takes the size from the meta file once its version is 3,
    and only from the header below that. A meta size that does not fit inside the
    file is not usable, so the header is read instead.
    """
    header_size = struct.unpack_from('<I', data, 0)[0]
    if meta and meta['version'] >= _META_VERSION_ACTUAL_SIZE and meta['actual_size'] is not None:
        if meta['actual_size'] <= len(data) - _HEADER_LENGTH:
            return meta['actual_size']
    return header_size


def _key_material(key, aes256=False):
    """Return the key bytes as AESCrypt takes them: truncated, then zero-padded.

    AESCrypt copies min(len(key), 16 or 32) bytes into a zero-filled buffer of
    that length, so a short key is padded with zeros and a long one is cut.
    """
    if isinstance(key, str):
        key = key.encode('utf-8')
    if not isinstance(key, (bytes, bytearray)):
        raise MMKVError('key must be bytes or a string')
    if not key:
        raise MMKVError('key is empty')
    length = _AES256_KEY_LENGTH if aes256 else _AES128_KEY_LENGTH
    return bytes(key[:length]).ljust(length, b'\x00')


def _decrypt(region, key, vector):
    """Decrypt a data region with AES-CFB128, the mode MMKV uses.

    Tries pycryptodome first, then cryptography. Neither is a dependency of this
    module: everything except decryption works with no packages installed.

    pycryptodome's MODE_CFB defaults to 8-bit segments, which silently returns
    something other than what MMKV wrote, so the segment size is passed
    explicitly. Both backends are checked against the published CFB128-AES128
    vector in the tests.
    """
    try:
        from Crypto.Cipher import AES  # pylint: disable=import-outside-toplevel
        return AES.new(key, AES.MODE_CFB, vector, segment_size=128).decrypt(region)
    except ImportError:
        pass
    try:
        # CFB moved to the decrepit module in cryptography 43 and is being removed
        # from the original location, so try its new home first.
        try:
            from cryptography.hazmat.decrepit.ciphers.modes import (  # pylint: disable=import-outside-toplevel
                CFB)
        except ImportError:
            from cryptography.hazmat.primitives.ciphers.modes import (  # pylint: disable=import-outside-toplevel
                CFB)
        from cryptography.hazmat.primitives.ciphers import (  # pylint: disable=import-outside-toplevel
            Cipher, algorithms)
        decryptor = Cipher(algorithms.AES(key), CFB(vector)).decryptor()
        return decryptor.update(region) + decryptor.finalize()
    except ImportError as exc:
        raise MMKVError('decrypting needs pycryptodome or cryptography installed; '
                        'neither was importable') from exc


def decode_value(container):
    """Decode a value container to a str or an int.

    A container that is exactly a varint length followed by that many bytes is
    how MMKV writes a string; anything else is read as a varint scalar, which
    covers its integer and boolean types. Returns None for a removal marker,
    and the raw bytes when neither reading applies.
    """
    if not container:
        return None
    try:
        length, offset = _read_varint(container, 0)
    except MMKVError:
        return container
    if offset + length == len(container):
        try:
            return container[offset:offset + length].decode('utf-8')
        except UnicodeDecodeError:
            return container[offset:offset + length]
    try:
        value, offset = _read_varint(container, 0)
    except MMKVError:
        return container
    if offset == len(container):
        return value
    return container


# A carved record is accepted only when its key looks like a key. The bounds and
# the character set come from the shape MMKV keys actually take: measured over
# 91,462 live records from four extractions, 1.4% of keys are shorter than 5 bytes
# and 2.0% longer than 64, which is the recall this window gives up. The space is
# deliberately absent. A space is byte 0x20, which is 32, so in running text it can
# serve as the key-length field and the 32 bytes after it read as a key; every one
# of the 2,469 false records a space-permitting version of this test produced on a
# megabyte of prose had a space in its key, and only 25 of those 91,462 real keys
# contain one.
_CARVE_KEY = re.compile(r'^[0-9\w\-\$\./:]+$')
_CARVE_KEY_MIN = 5
_CARVE_KEY_MAX = 64

CarvedRecord = collections.namedtuple('CarvedRecord', 'offset key container live_key')


def _carve_at(data, offset):
    """Return (key, container, end) if a record starts at ``offset``, else None."""
    end = len(data)
    try:
        key_length, position = _read_varint(data, offset)
    except MMKVError:
        return None
    if not _CARVE_KEY_MIN <= key_length <= _CARVE_KEY_MAX or position + key_length > end:
        return None
    try:
        key = data[position:position + key_length].decode('utf-8')
    except UnicodeDecodeError:
        return None
    if not _CARVE_KEY.match(key):
        return None
    position += key_length
    try:
        container_length, position = _read_varint(data, position)
    except MMKVError:
        return None
    if position + container_length > end:
        return None
    container = data[position:position + container_length]
    if container_length == 0:
        return key, container, position          # a removal marker
    try:
        inner, consumed = _read_varint(container, 0)
    except MMKVError:
        inner = None
    if inner is not None and (consumed == container_length
                              or inner == container_length - consumed):
        return key, container, position + container_length
    # MMKV writes float and double as raw little-endian, so those containers are
    # neither a length prefix nor a bare varint (CodedOutputData::writeFloat and
    # writeDouble); their width is the only thing that identifies them.
    if container_length in (4, 8):
        return key, container, position + container_length
    return None


def carve_slack(path):
    """Return records carved from the space past the recorded data region.

    Each result is a CarvedRecord: the record's absolute offset in the file, its
    key, its raw value container, and whether that key also exists in the live
    region. Results are in file order.

    **These are inferences, not parsed records, and some will be wrong.** The space
    holds earlier generations of this store, but a compaction overwrites the front
    of it, so the first surviving record rarely begins where the space does and the
    records are not contiguous. There is no marker to synchronise on, so every
    offset is tested on its own and anything structurally record-shaped is returned.

    What that costs, measured on data with no MMKV structure in it at all: zero
    false records per KiB on zero-filled, random, natural-language and JSON input,
    and about 1.2 per KiB on base64 and hex text, which no test here rules out. A
    store whose values are encoded blobs will therefore carve dirty. The signal that
    separates the two in practice is repetition: real carved records repeat a key,
    because that is what a superseded write is, and they overlap the live set, while
    the false ones are each unique and match nothing live. ``live_key`` carries that
    corroboration per record.

    Nothing returned here should reach a reader as an ordinary record. It is
    separate from read_entries for that reason, and read_dict never calls it.

    Raises MMKVError for a file that is not a readable MMKV store, and for an
    encrypted store, whose slack is ciphertext this does not attempt to read.
    """
    with open(path, 'rb') as handle:
        data = handle.read()
    if len(data) < _HEADER_LENGTH:
        raise MMKVError('file shorter than an MMKV header')
    meta = _read_meta(path)
    if meta and meta['vector']:
        raise MMKVError('cannot carve an encrypted store: the space past the recorded '
                        'region is ciphertext written under an earlier vector')
    region_size = _region_size(data, meta)
    start = _HEADER_LENGTH + region_size
    if start >= len(data):
        return []
    live = set()
    if region_size and start <= len(data):
        live = {entry_key for entry_key, _ in _walk(data[_HEADER_LENGTH:start])[0]}

    records = []
    offset = start
    while offset < len(data):
        found = _carve_at(data, offset)
        if found is None:
            offset += 1
            continue
        key, container, _ = found
        records.append(CarvedRecord(offset, key, container, key in live))
        offset += 1
    return records


def read_dict(path, key=None, aes256=False, recover=False):
    """Return {key: decoded value} using the last occurrence of each key.

    Removed keys are omitted. Use read_entries when the superseded values
    matter. ``key``, ``aes256`` and ``recover`` are passed through to read_entries.
    """
    result = {}
    for entry_key, container in read_entries(path, key=key, aes256=aes256, recover=recover):
        value = decode_value(container)
        if value is None:
            result.pop(entry_key, None)
        else:
            result[entry_key] = value
    return result
