# This list contains the filenames of artifact scripts that take a long time to run.
# These modules are deselected by default in the GUI.

modules_to_exclude = [
    'photosDbexif',
    'photosMetadata',
    'walStrings',
    'Ph008HasAdjustment',
    'Ph009BurstAvalanche',
    'Ph011KwrdsCapsTitlesDescripsBasicAssetData',
    'Ph015PeopleandDetFacesNAD',
    'Ph016AssetPeopleandDetFaces',
    'Ph017GenAIDetected',
    'Ph020AlbumsNAD',
    'Ph021AlbumsNonSharedNAD',
    'Ph022AssetsInNonSharedAlbums',
    'Ph023AlbumsSharedNAD',
    'Ph025SWYConvAlbumsNAD',
    'Ph024AssetsInSharedAlbums',
    'Ph026SyndicationPLAssets',
    'Ph030iCloudShareMethodsNAD',
    'Ph031iCloudSharePhotoLibraryNAD',
    'Ph032AssetsIniCldSPLwContrib',
    'Ph033AssetsIniCldSPLfromOtherContrib',
    'Ph034iCloudSharedLinksNAD',
    'Ph035iCloudSharedLinkAssets',
    'Ph050AssetIntResouData',
    'Ph051PossOptimizedAssetsIntResouData',
    'Ph094Ios14REFforAssetAnalysis',
    'Ph095iOS15REFforAssetAnalysis',
    'Ph096iOS16REFforAssetAnalysis',
    'Ph097iOS17REFforAssetAnalysis',
    'Ph098iOS18REFforAssetAnalysis',
    'Ph126iOS26REFforAssetAnalysis',
]