name: Python Lint Check

on:
  pull_request:
    paths:
      - '**.py' # only trigger on python files
jobs:
  lint-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Required to fetch the base branch for comparison
          fetch-depth: 0

      - name: Get changed Python files
        id: changed-files-py
        uses: tj-actions/changed-files@v46 # This action finds changed files
        with:
          files: |
            **.py

      - name: Set up Python
        if: steps.changed-files-py.outputs.any_changed == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Pylint
        if: steps.changed-files-py.outputs.any_changed == 'true'
        run: python -m pip install pylint

      - name: Run on changed files
        if: steps.changed-files-py.outputs.any_changed == 'true'
        run: |
          echo "Linting the following files:"
          echo "${{ steps.changed-files-py.outputs.all_changed_files }}"
          
          pylint ${{ steps.changed-files-py.outputs.all_changed_files }} --max-line-length=120 --reports y
